/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package pemviss3;

/**
 *
 * @author user
 */
public class apotek extends javax.swing.JFrame {
    private String[] namaObat;
    private String[] deskripsiObat;
    
    public apotek() {
    initComponents();
    
    namaObat = new String[]{"Paracetamol", "Ibuprofen", "Antibiotik", "Bodrex Extra", "Antivirus",
                            "Bodrex Flu dan Batuk", "Prome Sirup", "Comtusi", "Panadol", "Procold"};
    deskripsiObat = new String[]{
                "meredakan nyeri ringan hingga sedang dan menurunkan demam", //0
                "untuk mengurangi nyeri, peradangan, dan demam", //1
                "untuk mengobati infeksi bakteri", //2
                "Untuk sakit kepala yang lebih intens dan migrain", //3
                "Obat antivirus pada kasus infeksi virus yang berat", //4
                "Untuk meredakan flu, ex: demam, hidung tersumbat, batuk.", //5
                "Mengatasi batuk, terutama alergi", //6
                "Mengatasi flu dan batuk yang disertai batuk berdahak", //7
                "Meredakan demam dan nyeri otot yang mungkin muncul akibat flu", //8
                "Mengatasi flu, ex: demam, sakit kepala, hidung tersumbat" //9
        };
    }

 private void tampilkanObat(String gejala, String[] namaObat, String[] deskripsiObat) {
        switch (gejala) {
            case "Pusing":
                NamaObat.setText("Nama Obat : " + namaObat[9] +" dan " + namaObat[3]);
                Deskripsi.setText("Deskripsi : " + deskripsiObat[9] + " dan " + deskripsiObat[3]);
                break;
            case "Batuk":
                NamaObat.setText("Nama Obat : " + namaObat[6] + " dan " + namaObat[7]);
                Deskripsi.setText("Deskripsi : " + deskripsiObat[6] + " dan " + deskripsiObat[7]);
                break;
            case "Demam":
                NamaObat.setText("Nama Obat : " + namaObat[0] + " dan " + namaObat[1]);
                Deskripsi.setText("Deskripsi : " + deskripsiObat[0] + " dan " + deskripsiObat[1]);
                break;
            case "Pilek":
                NamaObat.setText("Nama Obat : " + namaObat[5] + " dan " + namaObat[7]);
                Deskripsi.setText("Deskripsi : " + deskripsiObat[5] + " dan " + deskripsiObat[7]);
                break;
            case "Nyeri Otot":
                NamaObat.setText("Nama Obat : " + namaObat[0] + " dan " + namaObat[8]);
                Deskripsi.setText("Deskripsi : " + deskripsiObat[0] + " dan " + deskripsiObat[8]);
                break;
//            default:
//                NamaObat.setText("Nama Obat:... ");
//                Deskripsi.setText("Deskripsi:... ");
               // break;
        }
    }
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Pusing = new javax.swing.JButton();
        Batuk = new javax.swing.JButton();
        Demam = new javax.swing.JButton();
        Flu = new javax.swing.JButton();
        Nyeriotot = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        NamaObat = new javax.swing.JLabel();
        Deskripsi = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        BodrexExtra = new javax.swing.JLabel();
        PromeSirup = new javax.swing.JLabel();
        Ibuprofen = new javax.swing.JLabel();
        Procold = new javax.swing.JLabel();
        Antibiotik = new javax.swing.JLabel();
        Comtusi = new javax.swing.JLabel();
        BodrexFluBatuk = new javax.swing.JLabel();
        Paracetamol = new javax.swing.JLabel();
        Panadol = new javax.swing.JLabel();
        Antivirus = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel4.setBackground(new java.awt.Color(204, 204, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("APOTEK  MINI");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 20, -1, -1));

        jLabel2.setText("Jl. Raya Galis");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(675, 54, -1, -1));

        jLabel3.setText("Gejala Penyakit :");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 87, -1, -1));

        Pusing.setText("Sakit Kepala");
        Pusing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PusingActionPerformed(evt);
            }
        });
        jPanel4.add(Pusing, new org.netbeans.lib.awtextra.AbsoluteConstraints(296, 83, -1, -1));

        Batuk.setText("Batuk");
        Batuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BatukActionPerformed(evt);
            }
        });
        jPanel4.add(Batuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(483, 83, -1, -1));

        Demam.setText("Demam");
        Demam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DemamActionPerformed(evt);
            }
        });
        jPanel4.add(Demam, new org.netbeans.lib.awtextra.AbsoluteConstraints(685, 83, -1, -1));

        Flu.setText("Pilek");
        Flu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FluActionPerformed(evt);
            }
        });
        jPanel4.add(Flu, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 80, -1, -1));

        Nyeriotot.setText("Nyeri Otot");
        Nyeriotot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NyeriototActionPerformed(evt);
            }
        });
        jPanel4.add(Nyeriotot, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 80, -1, -1));

        jLabel4.setText("__________________________________________________________________________________________________________________________________________________________________________________");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 137, -1, -1));

        getContentPane().add(jPanel4, java.awt.BorderLayout.PAGE_START);

        jPanel5.setLayout(new java.awt.GridBagLayout());

        jLabel16.setText("_____________________________________________________________________________________________________________________________________________________________________");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 0;
        jPanel5.add(jLabel16, gridBagConstraints);

        jLabel6.setText("  ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel5.add(jLabel6, gridBagConstraints);

        NamaObat.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        NamaObat.setText("Nama Obat : ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel5.add(NamaObat, gridBagConstraints);

        Deskripsi.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Deskripsi.setText("Deskripsi : ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel5.add(Deskripsi, gridBagConstraints);

        jLabel5.setText("  ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        jPanel5.add(jLabel5, gridBagConstraints);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setText("SARAN OBAT ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel5.add(jLabel7, gridBagConstraints);

        getContentPane().add(jPanel5, java.awt.BorderLayout.PAGE_END);

        jPanel6.setLayout(new java.awt.GridLayout(2, 5));

        BodrexExtra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pemviss3/bodrex extra.jpeg"))); // NOI18N
        BodrexExtra.setText("Bodrex Extra");
        jPanel6.add(BodrexExtra);

        PromeSirup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pemviss3/prome sirup.png"))); // NOI18N
        PromeSirup.setText("Prome Sirup ");
        jPanel6.add(PromeSirup);

        Ibuprofen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pemviss3/ibuprofen.jpg"))); // NOI18N
        Ibuprofen.setText("Ibuprofen");
        jPanel6.add(Ibuprofen);

        Procold.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pemviss3/proclod.png"))); // NOI18N
        Procold.setText("Procold");
        jPanel6.add(Procold);

        Antibiotik.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pemviss3/antibiotik.jpg"))); // NOI18N
        Antibiotik.setText("Antibiotik");
        jPanel6.add(Antibiotik);

        Comtusi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pemviss3/comtusi.png"))); // NOI18N
        Comtusi.setText("Comtusi");
        jPanel6.add(Comtusi);

        BodrexFluBatuk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pemviss3/bodrex flu & batuk.jpeg"))); // NOI18N
        BodrexFluBatuk.setText("Bodrex Flu & Batuk");
        jPanel6.add(BodrexFluBatuk);

        Paracetamol.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pemviss3/paracetamol.png"))); // NOI18N
        Paracetamol.setText("Paracetamol");
        jPanel6.add(Paracetamol);

        Panadol.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pemviss3/panadol.png"))); // NOI18N
        Panadol.setText("Panadol");
        jPanel6.add(Panadol);

        Antivirus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pemviss3/antivirus.png"))); // NOI18N
        Antivirus.setText("Antivirus");
        jPanel6.add(Antivirus);

        getContentPane().add(jPanel6, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PusingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PusingActionPerformed
    tampilkanObat("Pusing", namaObat, deskripsiObat);        
// TODO add your handling code here:
    }//GEN-LAST:event_PusingActionPerformed

    private void BatukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BatukActionPerformed
    tampilkanObat("Batuk", namaObat, deskripsiObat);
    // TODO add your handling code here:
    }//GEN-LAST:event_BatukActionPerformed

    private void DemamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DemamActionPerformed
    tampilkanObat("Demam", namaObat, deskripsiObat);
    // TODO add your handling code here:
    }//GEN-LAST:event_DemamActionPerformed

    private void FluActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FluActionPerformed
    tampilkanObat("Pilek", namaObat, deskripsiObat);
    // TODO add your handling code here:
    }//GEN-LAST:event_FluActionPerformed

    private void NyeriototActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NyeriototActionPerformed
    tampilkanObat("Nyeri Otot", namaObat, deskripsiObat);
    // TODO add your handling code here:
    }//GEN-LAST:event_NyeriototActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(apotek.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(apotek.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(apotek.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(apotek.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new apotek().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Antibiotik;
    private javax.swing.JLabel Antivirus;
    private javax.swing.JButton Batuk;
    private javax.swing.JLabel BodrexExtra;
    private javax.swing.JLabel BodrexFluBatuk;
    private javax.swing.JLabel Comtusi;
    private javax.swing.JButton Demam;
    private javax.swing.JLabel Deskripsi;
    private javax.swing.JButton Flu;
    private javax.swing.JLabel Ibuprofen;
    private javax.swing.JLabel NamaObat;
    private javax.swing.JButton Nyeriotot;
    private javax.swing.JLabel Panadol;
    private javax.swing.JLabel Paracetamol;
    private javax.swing.JLabel Procold;
    private javax.swing.JLabel PromeSirup;
    private javax.swing.JButton Pusing;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    // End of variables declaration//GEN-END:variables

}
