/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package praktikum1;

/**
 *
 * @author HP
 */
public class DataPendaftar extends javax.swing.JFrame {

    /**
     * Creates new form DataPendaftar
     */
    public DataPendaftar() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        lblnama = new javax.swing.JLabel();
        alamatLengkap = new javax.swing.JLabel();
        nomortelpon = new javax.swing.JLabel();
        jeniskelamin = new javax.swing.JLabel();
        lesDiambil = new javax.swing.JLabel();
        jadwal = new javax.swing.JLabel();
        biaya = new javax.swing.JLabel();
        pembayaran = new javax.swing.JLabel();
        tfnamapendaftar = new javax.swing.JTextField();
        tfalamatlengkap = new javax.swing.JTextField();
        tfnomortelepon = new javax.swing.JTextField();
        tfjeniskelamin = new javax.swing.JTextField();
        tfLesyangdiambil = new javax.swing.JTextField();
        tfjadwalLes = new javax.swing.JTextField();
        tfbiayaLes = new javax.swing.JTextField();
        tfjenisPembayaran = new javax.swing.JTextField();
        email = new javax.swing.JLabel();
        tfEmail = new javax.swing.JTextField();
        btnkeluar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 153, 153));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblnama.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblnama.setText("Nama                           :");
        jPanel3.add(lblnama, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 49, 140, -1));

        alamatLengkap.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        alamatLengkap.setText("Alamat                         :");
        jPanel3.add(alamatLengkap, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 89, 140, -1));

        nomortelpon.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        nomortelpon.setText("Nomor Telepon           :");
        jPanel3.add(nomortelpon, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 124, 140, -1));

        jeniskelamin.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jeniskelamin.setText("Jenis Kelamin             :");
        jPanel3.add(jeniskelamin, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 164, 140, -1));

        lesDiambil.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lesDiambil.setText("Les yang diambil         :");
        jPanel3.add(lesDiambil, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 204, 140, -1));

        jadwal.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jadwal.setText("Jadwal Les                   :");
        jPanel3.add(jadwal, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 244, 140, -1));

        biaya.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        biaya.setText("Biaya Les                      :");
        jPanel3.add(biaya, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 279, 140, -1));

        pembayaran.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        pembayaran.setText("Jenis Pembayaran       :");
        jPanel3.add(pembayaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 322, 140, -1));

        tfnamapendaftar.setEditable(false);
        tfnamapendaftar.setBackground(new java.awt.Color(255, 255, 255));
        tfnamapendaftar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jPanel3.add(tfnamapendaftar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 250, 30));

        tfalamatlengkap.setEditable(false);
        tfalamatlengkap.setBackground(new java.awt.Color(255, 255, 255));
        tfalamatlengkap.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        tfalamatlengkap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfalamatlengkapActionPerformed(evt);
            }
        });
        jPanel3.add(tfalamatlengkap, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 86, 250, 30));

        tfnomortelepon.setEditable(false);
        tfnomortelepon.setBackground(new java.awt.Color(255, 255, 255));
        tfnomortelepon.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        tfnomortelepon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfnomorteleponActionPerformed(evt);
            }
        });
        jPanel3.add(tfnomortelepon, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 121, 250, 30));

        tfjeniskelamin.setEditable(false);
        tfjeniskelamin.setBackground(new java.awt.Color(255, 255, 255));
        tfjeniskelamin.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        tfjeniskelamin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfjeniskelaminActionPerformed(evt);
            }
        });
        jPanel3.add(tfjeniskelamin, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 161, 250, 30));

        tfLesyangdiambil.setEditable(false);
        tfLesyangdiambil.setBackground(new java.awt.Color(255, 255, 255));
        tfLesyangdiambil.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jPanel3.add(tfLesyangdiambil, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 201, 250, 30));

        tfjadwalLes.setEditable(false);
        tfjadwalLes.setBackground(new java.awt.Color(255, 255, 255));
        tfjadwalLes.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jPanel3.add(tfjadwalLes, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 241, 250, 30));

        tfbiayaLes.setEditable(false);
        tfbiayaLes.setBackground(new java.awt.Color(255, 255, 255));
        tfbiayaLes.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        tfbiayaLes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfbiayaLesActionPerformed(evt);
            }
        });
        jPanel3.add(tfbiayaLes, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 279, 250, 30));

        tfjenisPembayaran.setEditable(false);
        tfjenisPembayaran.setBackground(new java.awt.Color(255, 255, 255));
        tfjenisPembayaran.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jPanel3.add(tfjenisPembayaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 319, 250, 30));

        email.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        email.setText("Email                             : ");
        jPanel3.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 150, -1));

        tfEmail.setEditable(false);
        tfEmail.setBackground(new java.awt.Color(255, 255, 255));
        tfEmail.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jPanel3.add(tfEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 360, 250, 30));

        btnkeluar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnkeluar.setText("Keluar");
        btnkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkeluarActionPerformed(evt);
            }
        });
        jPanel3.add(btnkeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 440, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\Documents\\NetBeansProjects\\Praktikum1\\src\\praktikum1\\aaaaaa.png")); // NOI18N
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 550));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 470, 550));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\Downloads\\an.png")); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\Downloads\\as.png")); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, 70, 60));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("Formulir Pendaftaran Peserta Private Les");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N
        jLabel5.setText("Jl.Ketapang Besar 36 A, Kec. Semampir, Kel. Ampel");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, -1, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N
        jLabel6.setText(" Surabaya, Jawa Timur, 60151");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 55, -1, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 82));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tfalamatlengkapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfalamatlengkapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfalamatlengkapActionPerformed

    private void tfbiayaLesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfbiayaLesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfbiayaLesActionPerformed

    private void tfnomorteleponActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfnomorteleponActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfnomorteleponActionPerformed

    private void tfjeniskelaminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfjeniskelaminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfjeniskelaminActionPerformed

    private void btnkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkeluarActionPerformed
          btnkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                // Fungsi untuk menutup aplikasi
                System.exit(0);
            }
        });
    }//GEN-LAST:event_btnkeluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DataPendaftar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DataPendaftar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DataPendaftar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataPendaftar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DataPendaftar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel alamatLengkap;
    public javax.swing.JLabel biaya;
    private javax.swing.JButton btnkeluar;
    public javax.swing.JLabel email;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JPanel jPanel3;
    public javax.swing.JLabel jadwal;
    public javax.swing.JLabel jeniskelamin;
    public javax.swing.JLabel lblnama;
    public javax.swing.JLabel lesDiambil;
    public javax.swing.JLabel nomortelpon;
    public javax.swing.JLabel pembayaran;
    public javax.swing.JTextField tfEmail;
    public javax.swing.JTextField tfLesyangdiambil;
    public javax.swing.JTextField tfalamatlengkap;
    public javax.swing.JTextField tfbiayaLes;
    public javax.swing.JTextField tfjadwalLes;
    public javax.swing.JTextField tfjenisPembayaran;
    public javax.swing.JTextField tfjeniskelamin;
    public javax.swing.JTextField tfnamapendaftar;
    public javax.swing.JTextField tfnomortelepon;
    // End of variables declaration//GEN-END:variables
}
