/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tugasprktkm2;


import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author amand
 */
public class Bakery extends javax.swing.JFrame {

    double pembayaran = 0;
    double kembalian = 0;


    public Bakery() {
        initComponents();
        tfkembalian.setEditable(false);
        tftotal.setEditable(false);
        tfdiskon.setEditable(false);
        tfhb.setEditable(false); 
        
        tfpembayaran.addKeyListener(new KeyAdapter() {
            public void keyReleased(KeyEvent e) {
                hitung();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgmenu = new javax.swing.ButtonGroup();
        bgtopping = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        croissant = new javax.swing.JRadioButton();
        brioche = new javax.swing.JRadioButton();
        bagel = new javax.swing.JRadioButton();
        SB = new javax.swing.JRadioButton();
        BananaBread = new javax.swing.JRadioButton();
        CiRoll = new javax.swing.JRadioButton();
        waffle = new javax.swing.JRadioButton();
        GarBread = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        ToppingKeju = new javax.swing.JRadioButton();
        ToppingCoklat = new javax.swing.JRadioButton();
        NoTopping = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btnkurang = new javax.swing.JButton();
        btntambah = new javax.swing.JButton();
        tfjumlah = new javax.swing.JTextField();
        tftotal = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tfpembayaran = new javax.swing.JTextField();
        tfkembalian = new javax.swing.JTextField();
        btnreset = new javax.swing.JButton();
        btnbayar = new javax.swing.JButton();
        btnbatal = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tfdiskon = new javax.swing.JTextField();
        tfhb = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Perpetua Titling MT", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("La Creme Bakery");

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\amand\\Downloads\\Bakery.png")); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\amand\\Downloads\\kue (1).png")); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel8)
                .addGap(86, 86, 86)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(37, 37, 37))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel5)
                        .addComponent(jLabel8)))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 90));

        jPanel1.setBackground(new java.awt.Color(255, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setFont(new java.awt.Font("Perpetua Titling MT", 3, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("-----MENU ROTI-----");

        bgmenu.add(croissant);
        croissant.setFont(new java.awt.Font("Perpetua Titling MT", 0, 12)); // NOI18N
        croissant.setText("Croissant - Rp 25,000");

        bgmenu.add(brioche);
        brioche.setFont(new java.awt.Font("Perpetua Titling MT", 0, 12)); // NOI18N
        brioche.setText("Brioche - Rp 30,000");

        bgmenu.add(bagel);
        bagel.setFont(new java.awt.Font("Perpetua Titling MT", 0, 12)); // NOI18N
        bagel.setText("Bagel - Rp 28,000 ");

        bgmenu.add(SB);
        SB.setFont(new java.awt.Font("Perpetua Titling MT", 0, 12)); // NOI18N
        SB.setText("Sourdough Bread - Rp 35,000");

        bgmenu.add(BananaBread);
        BananaBread.setFont(new java.awt.Font("Perpetua Titling MT", 0, 12)); // NOI18N
        BananaBread.setText("Banana Bread - Rp 20,000");

        bgmenu.add(CiRoll);
        CiRoll.setFont(new java.awt.Font("Perpetua Titling MT", 0, 12)); // NOI18N
        CiRoll.setText("Cinnamon Roll - Rp 18,000");

        bgmenu.add(waffle);
        waffle.setFont(new java.awt.Font("Perpetua Titling MT", 0, 12)); // NOI18N
        waffle.setText("Waffle - Rp 15,000");

        bgmenu.add(GarBread);
        GarBread.setFont(new java.awt.Font("Perpetua Titling MT", 0, 12)); // NOI18N
        GarBread.setText("Garlic Bread - Rp 21,000");

        jLabel3.setFont(new java.awt.Font("Perpetua Titling MT", 3, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("------TOPPING-----");

        bgtopping.add(ToppingKeju);
        ToppingKeju.setFont(new java.awt.Font("Perpetua Titling MT", 0, 12)); // NOI18N
        ToppingKeju.setText("Keju - Rp 5,000");

        bgtopping.add(ToppingCoklat);
        ToppingCoklat.setFont(new java.awt.Font("Perpetua Titling MT", 0, 12)); // NOI18N
        ToppingCoklat.setText("COKLAT- Rp 3,000");
        ToppingCoklat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ToppingCoklatActionPerformed(evt);
            }
        });

        bgtopping.add(NoTopping);
        NoTopping.setFont(new java.awt.Font("Perpetua Titling MT", 0, 12)); // NOI18N
        NoTopping.setText("No Topping - Rp 0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bagel)
                            .addComponent(croissant)
                            .addComponent(BananaBread)
                            .addComponent(waffle)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(ToppingKeju)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                        .addComponent(ToppingCoklat)))
                .addGap(49, 49, 49))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(GarBread)
                        .addGap(58, 58, 58))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(CiRoll)
                        .addGap(39, 39, 39))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(SB)
                        .addGap(21, 21, 21))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(brioche)
                        .addGap(92, 92, 92))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(NoTopping, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(29, 29, 29)
                .addComponent(croissant)
                .addGap(12, 12, 12)
                .addComponent(brioche)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bagel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BananaBread)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CiRoll)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(waffle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(GarBread)
                .addGap(29, 29, 29)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ToppingKeju)
                    .addComponent(ToppingCoklat))
                .addGap(18, 18, 18)
                .addComponent(NoTopping)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 340, 450));

        jPanel3.setBackground(new java.awt.Color(255, 153, 153));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel4.setFont(new java.awt.Font("Perpetua Titling MT", 3, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("JUMLAH Roti :");

        btnkurang.setBackground(new java.awt.Color(255, 102, 102));
        btnkurang.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        btnkurang.setText("-");
        btnkurang.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnkurang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkurangActionPerformed(evt);
            }
        });

        btntambah.setBackground(new java.awt.Color(255, 102, 102));
        btntambah.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        btntambah.setText("+");
        btntambah.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btntambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntambahActionPerformed(evt);
            }
        });

        tfjumlah.setBackground(new java.awt.Color(0, 0, 0));
        tfjumlah.setFont(new java.awt.Font("Baskerville Old Face", 1, 24)); // NOI18N
        tfjumlah.setForeground(new java.awt.Color(255, 255, 255));
        tfjumlah.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfjumlah.setText("0");
        tfjumlah.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        tftotal.setFont(new java.awt.Font("Baskerville Old Face", 1, 15)); // NOI18N
        tftotal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tftotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tftotalActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Perpetua Titling MT", 3, 12)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("PEMBAYARAN :");

        jLabel7.setFont(new java.awt.Font("Perpetua Titling MT", 3, 12)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("KEMBALIAN :");

        tfpembayaran.setFont(new java.awt.Font("Baskerville Old Face", 1, 15)); // NOI18N
        tfpembayaran.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        tfkembalian.setFont(new java.awt.Font("Baskerville Old Face", 1, 15)); // NOI18N
        tfkembalian.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfkembalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfkembalianActionPerformed(evt);
            }
        });

        btnreset.setBackground(new java.awt.Color(255, 102, 102));
        btnreset.setFont(new java.awt.Font("Perpetua Titling MT", 3, 14)); // NOI18N
        btnreset.setIcon(new javax.swing.ImageIcon("C:\\Users\\amand\\Downloads\\reset (1) (1).png")); // NOI18N
        btnreset.setText("RESET");
        btnreset.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnresetActionPerformed(evt);
            }
        });

        btnbayar.setBackground(new java.awt.Color(255, 102, 102));
        btnbayar.setFont(new java.awt.Font("Perpetua Titling MT", 3, 14)); // NOI18N
        btnbayar.setText("BAYAR");
        btnbayar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnbayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbayarActionPerformed(evt);
            }
        });

        btnbatal.setBackground(new java.awt.Color(255, 102, 102));
        btnbatal.setFont(new java.awt.Font("Perpetua Titling MT", 3, 14)); // NOI18N
        btnbatal.setText("KELUAR");
        btnbatal.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnbatal.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnbatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbatalActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Perpetua Titling MT", 3, 12)); // NOI18N
        jLabel9.setText("TOTAL :");

        jLabel10.setFont(new java.awt.Font("Perpetua Titling MT", 3, 12)); // NOI18N
        jLabel10.setText("DISKON :");

        tfdiskon.setFont(new java.awt.Font("Baskerville Old Face", 1, 15)); // NOI18N

        tfhb.setFont(new java.awt.Font("Baskerville Old Face", 1, 15)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Perpetua Titling MT", 3, 12)); // NOI18N
        jLabel11.setText("HARGA YANG DIBAYAR :");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tfjumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnkurang, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                                    .addComponent(btntambah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(150, 150, 150))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(155, 155, 155)))
                        .addGap(54, 54, 54))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnbayar, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnbatal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnreset, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(198, 198, 198))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(103, 103, 103)
                                .addComponent(tftotal, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tfdiskon, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(tfhb, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(tfpembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(tfkembalian, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(35, 35, 35))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(btnkurang)
                        .addGap(12, 12, 12)
                        .addComponent(btntambah))
                    .addComponent(tfjumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tftotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(tfdiskon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfhb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tfpembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfkembalian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(58, 58, 58)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnbatal, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnreset)
                    .addComponent(btnbayar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(25, 25, 25))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 90, 370, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void hitung() {
        try {
            double hargaygdibayar = Double.parseDouble(tfhb.getText());
            double uangmasuk = Double.parseDouble(tfpembayaran.getText());
            double kembalian = uangmasuk - hargaygdibayar;

            if (kembalian >= 0) {
                tfkembalian.setText(String.valueOf(kembalian));
            } else {
                tfkembalian.setText("Uang Tidak Cukup");
            }
            
        } catch (NumberFormatException e) {
          tfkembalian.setText("Input Tidak Sesuai");
        }
    }
    private void btnkurangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkurangActionPerformed
        // TODO add your handling code here:
        int jumlah = Integer.parseInt(tfjumlah.getText());
            if (jumlah >= 1) {
            jumlah = jumlah - 1;
        }
        tfjumlah.setText(String.valueOf(jumlah));
        
    }//GEN-LAST:event_btnkurangActionPerformed

    private void btntambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntambahActionPerformed
        // TODO add your handling code here:
        int jumlah = Integer.parseInt(tfjumlah.getText());
            jumlah = jumlah + 1;
        tfjumlah.setText(String.valueOf(jumlah));
    }//GEN-LAST:event_btntambahActionPerformed

    private void btnbayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbayarActionPerformed

        if (bgmenu.getSelection() == null || bgtopping.getSelection() == null) {
        JOptionPane.showMessageDialog(null, "Harap pilih menu roti dan topping dahulu!");
        } else if (Integer.parseInt(tfjumlah.getText()) <= 0) { 
            JOptionPane.showMessageDialog(null, "Jumlah pembelian minimal 1!", "Peringatan", JOptionPane.WARNING_MESSAGE);
        } 
        
        double harga = 0;
        double diskon = 0;
        
        
        
        if (croissant.isSelected()){
                String jumlahpesanan = tfjumlah.getText();
                harga += 25000 * Integer.parseInt(jumlahpesanan);
                if (ToppingKeju.isSelected()){
                    harga += 5000 * Integer.parseInt(jumlahpesanan);
                } else if (ToppingCoklat.isSelected()){
                    harga += 3000 * Integer.parseInt(jumlahpesanan);
                } else if (NoTopping.isSelected()) {
                    harga += 0; 
                }
                tftotal.setText(String.valueOf(harga));
                    if (harga > 100000) {
                        diskon = harga * 0.05;
                        tfdiskon.setText(String.valueOf(diskon));
                        harga -= diskon;
                        tfhb.setText(String.valueOf(harga));
                    } else {
                        tfdiskon.setText("0");
                        tfhb.setText(String.valueOf(harga));
                    }
        }
        else if (brioche.isSelected()){
                String jumlahpesanan = tfjumlah.getText();
                harga += 30000 * Integer.parseInt(jumlahpesanan);
                if (ToppingKeju.isSelected()){
                    harga += 5000 * Integer.parseInt(jumlahpesanan);
                } else if (ToppingCoklat.isSelected()){
                    harga += 3000 * Integer.parseInt(jumlahpesanan);
                } else if (NoTopping.isSelected()) {
                    harga += 0; 
                }
                tftotal.setText(String.valueOf(harga));
                    if (harga > 100000) {
                        diskon = harga * 0.05;
                        tfdiskon.setText(String.valueOf(diskon));
                        harga -= diskon;
                        tfhb.setText(String.valueOf(harga));
                    } else {
                        tfdiskon.setText("0");
                        tfhb.setText(String.valueOf(harga));
                    }
        }
        else if (bagel.isSelected()){
                String jumlahpesanan = tfjumlah.getText();
                harga += 28000 * Integer.parseInt(jumlahpesanan);
                if (ToppingKeju.isSelected()){
                    harga += 5000 * Integer.parseInt(jumlahpesanan);
                } else if (ToppingCoklat.isSelected()){
                    harga += 3000 * Integer.parseInt(jumlahpesanan);
                } else if (NoTopping.isSelected()) {
                    harga += 0; 
                }
                tftotal.setText(String.valueOf(harga));
                    if (harga > 100000) {
                        diskon = harga * 0.05;
                        tfdiskon.setText(String.valueOf(diskon));
                        harga -= diskon;
                        tfhb.setText(String.valueOf(harga));
                    } else {
                        tfdiskon.setText("0");
                        tfhb.setText(String.valueOf(harga));
                    }
        }
        else if (SB.isSelected()){
                String jumlahpesanan = tfjumlah.getText();
                harga += 35000 * Integer.parseInt(jumlahpesanan);
                if (ToppingKeju.isSelected()){
                    harga += 5000 * Integer.parseInt(jumlahpesanan);
                } else if (ToppingCoklat.isSelected()){
                    harga += 3000 * Integer.parseInt(jumlahpesanan);
                } else if (NoTopping.isSelected()) {
                    harga += 0; 
                }
                tftotal.setText(String.valueOf(harga));
                    if (harga > 100000) {
                        diskon = harga * 0.05;
                        tfdiskon.setText(String.valueOf(diskon));
                        harga -= diskon;
                        tfhb.setText(String.valueOf(harga));
                    } else {
                        tfdiskon.setText("0");
                        tfhb.setText(String.valueOf(harga));
                    }
        }
        else if (BananaBread.isSelected()){
                String jumlahpesanan = tfjumlah.getText();
                harga += 20000 * Integer.parseInt(jumlahpesanan);
                if (ToppingKeju.isSelected()){
                    harga += 5000 * Integer.parseInt(jumlahpesanan);
                } else if (ToppingCoklat.isSelected()){
                    harga += 3000 * Integer.parseInt(jumlahpesanan);
                } else if (NoTopping.isSelected()) {
                    harga += 0; 
                }
                tftotal.setText(String.valueOf(harga));
                    if (harga > 100000) {
                        diskon = harga * 0.05;
                        tfdiskon.setText(String.valueOf(diskon));
                        harga -= diskon;
                        tfhb.setText(String.valueOf(harga));
                    } else {
                        tfdiskon.setText("0");
                        tfhb.setText(String.valueOf(harga));
                    }
        }
        else if (CiRoll.isSelected()){
                String jumlahpesanan = tfjumlah.getText();
                harga += 18000 * Integer.parseInt(jumlahpesanan);
                if (ToppingKeju.isSelected()){
                    harga += 5000 * Integer.parseInt(jumlahpesanan);
                } else if (ToppingCoklat.isSelected()){
                    harga += 3000 * Integer.parseInt(jumlahpesanan);
                } else if (NoTopping.isSelected()) {
                    harga += 0; 
                }
                tftotal.setText(String.valueOf(harga));
                    if (harga > 100000) {
                        diskon = harga * 0.05;
                        tfdiskon.setText(String.valueOf(diskon));
                        harga -= diskon;
                        tfhb.setText(String.valueOf(harga));
                    } else {
                        tfdiskon.setText("0");
                        tfhb.setText(String.valueOf(harga));
                    }
        }
        else if (waffle.isSelected()){
                String jumlahpesanan = tfjumlah.getText();
                harga += 15000 * Integer.parseInt(jumlahpesanan);
                if (ToppingKeju.isSelected()){
                    harga += 5000 * Integer.parseInt(jumlahpesanan);
                } else if (ToppingCoklat.isSelected()){
                    harga += 3000 * Integer.parseInt(jumlahpesanan);
                } else if (NoTopping.isSelected()) {
                    harga += 0; 
                }
                tftotal.setText(String.valueOf(harga));
                    if (harga > 100000) {
                        diskon = harga * 0.05;
                        tfdiskon.setText(String.valueOf(diskon));
                        harga -= diskon;
                        tfhb.setText(String.valueOf(harga));
                    } else {
                        tfdiskon.setText("0");
                        tfhb.setText(String.valueOf(harga));
                    }
        }
        else if (GarBread.isSelected()){
                String jumlahpesanan = tfjumlah.getText();
                harga += 21000 * Integer.parseInt(jumlahpesanan);
                if (ToppingKeju.isSelected()){
                    harga += 5000 * Integer.parseInt(jumlahpesanan);
                } else if (ToppingCoklat.isSelected()){
                    harga += 3000 * Integer.parseInt(jumlahpesanan);
                } else if (NoTopping.isSelected()) {
                    harga += 0; 
                }
                tftotal.setText(String.valueOf(harga));
                    if (harga > 100000) {
                        diskon = harga * 0.05;
                        tfdiskon.setText(String.valueOf(diskon));
                        harga -= diskon;
                        tfhb.setText(String.valueOf(harga));
                    } else {
                        tfdiskon.setText("0");
                        tfhb.setText(String.valueOf(harga));
                    }
        }
    }//GEN-LAST:event_btnbayarActionPerformed

    private void btnresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnresetActionPerformed
        // TODO add your handling code here:
        bgmenu.clearSelection();
        bgtopping.clearSelection();
        tftotal.setText("");
        int jumlah = 0;
        tfjumlah.setText(String.valueOf(jumlah));
        tfpembayaran.setText("");
        tfkembalian.setText("");
        tfdiskon.setText("");
        tfhb.setText("");
    }//GEN-LAST:event_btnresetActionPerformed

    private void ToppingCoklatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ToppingCoklatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ToppingCoklatActionPerformed

    private void tftotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tftotalActionPerformed
        // TODO add your handling code here:
  
    }//GEN-LAST:event_tftotalActionPerformed

    private void tfkembalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfkembalianActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfkembalianActionPerformed

    private void btnbatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbatalActionPerformed
        // TODO add your handling code here:
         if (JOptionPane.showConfirmDialog(null, "Yakin Ingin Keluar?", "Konfirmasi Keluar", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_btnbatalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bakery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bakery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bakery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bakery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bakery().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton BananaBread;
    private javax.swing.JRadioButton CiRoll;
    private javax.swing.JRadioButton GarBread;
    private javax.swing.JRadioButton NoTopping;
    private javax.swing.JRadioButton SB;
    private javax.swing.JRadioButton ToppingCoklat;
    private javax.swing.JRadioButton ToppingKeju;
    private javax.swing.JRadioButton bagel;
    private javax.swing.ButtonGroup bgmenu;
    private javax.swing.ButtonGroup bgtopping;
    private javax.swing.JRadioButton brioche;
    private javax.swing.JButton btnbatal;
    private javax.swing.JButton btnbayar;
    public javax.swing.JButton btnkurang;
    private javax.swing.JButton btnreset;
    private javax.swing.JButton btntambah;
    private javax.swing.JRadioButton croissant;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField tfdiskon;
    private javax.swing.JTextField tfhb;
    private javax.swing.JTextField tfjumlah;
    private javax.swing.JTextField tfkembalian;
    private javax.swing.JTextField tfpembayaran;
    private javax.swing.JTextField tftotal;
    private javax.swing.JRadioButton waffle;
    // End of variables declaration//GEN-END:variables
}
