/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package modul2;

import javax.swing.*;

/**
 *
 * @author asus
 */
public class PemesanannRoti extends javax.swing.JFrame {

    private int quantity = 0;
    private int total = 0;
    private int breadPrice = 0;
    private int toppingPrice = 0;
    private int totalToppingPrice = 0;
    
    public PemesanannRoti() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btgrpMenu = new javax.swing.ButtonGroup();
        btgrpTopping = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        rbChocoCheese = new javax.swing.JRadioButton();
        rbPillowCokelat = new javax.swing.JRadioButton();
        rbFlossRoll = new javax.swing.JRadioButton();
        rbChickenFloss = new javax.swing.JRadioButton();
        rbAbonRoll = new javax.swing.JRadioButton();
        rbEggBun = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnMin = new javax.swing.JButton();
        tfJumlah = new javax.swing.JTextField();
        btnPlus = new javax.swing.JButton();
        btnTotal = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        tfTotal = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        tfCash = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        tfKembali = new javax.swing.JTextField();
        btnReset = new javax.swing.JButton();
        cbChococips = new javax.swing.JCheckBox();
        cbChocoCrunch = new javax.swing.JCheckBox();
        cbStrawberry = new javax.swing.JCheckBox();
        cbKeju = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon("E:\\tugas\\semester3\\1000364382-removebg-preview.png")); // NOI18N

        jLabel2.setFont(new java.awt.Font("Baskerville Old Face", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 153, 0));
        jLabel2.setText("ROTI");

        jLabel3.setFont(new java.awt.Font("Baskerville Old Face", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 153, 0));
        jLabel3.setText("KITA");

        jLabel4.setFont(new java.awt.Font("Baskerville Old Face", 1, 36)); // NOI18N
        jLabel4.setText("BAKERY");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(193, 193, 193)
                        .addComponent(jLabel4)))
                .addContainerGap(210, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 120));

        jPanel2.setBackground(new java.awt.Color(0, 102, 51));

        jLabel5.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("MENU ROTI");

        btgrpMenu.add(rbChocoCheese);
        rbChocoCheese.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        rbChocoCheese.setForeground(new java.awt.Color(255, 255, 255));
        rbChocoCheese.setText("Choco Cheese - Rp. 20.500");
        rbChocoCheese.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbChocoCheeseActionPerformed(evt);
            }
        });

        btgrpMenu.add(rbPillowCokelat);
        rbPillowCokelat.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        rbPillowCokelat.setForeground(new java.awt.Color(255, 255, 255));
        rbPillowCokelat.setText("Pillow Cokelat - Rp. 20.000");
        rbPillowCokelat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbPillowCokelatActionPerformed(evt);
            }
        });

        btgrpMenu.add(rbFlossRoll);
        rbFlossRoll.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        rbFlossRoll.setForeground(new java.awt.Color(255, 255, 255));
        rbFlossRoll.setText("Floss Roll - Rp. 10.500");
        rbFlossRoll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbFlossRollActionPerformed(evt);
            }
        });

        btgrpMenu.add(rbChickenFloss);
        rbChickenFloss.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        rbChickenFloss.setForeground(new java.awt.Color(255, 255, 255));
        rbChickenFloss.setText("Chicken Floss - Rp. 15.000");
        rbChickenFloss.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbChickenFlossActionPerformed(evt);
            }
        });

        btgrpMenu.add(rbAbonRoll);
        rbAbonRoll.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        rbAbonRoll.setForeground(new java.awt.Color(255, 255, 255));
        rbAbonRoll.setText("Abon Roll - Rp. 22.000");
        rbAbonRoll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbAbonRollActionPerformed(evt);
            }
        });

        btgrpMenu.add(rbEggBun);
        rbEggBun.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        rbEggBun.setForeground(new java.awt.Color(255, 255, 255));
        rbEggBun.setText("Egg Bun - Rp. 13.000");
        rbEggBun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbEggBunActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("TOPPING");

        jLabel7.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("JUMLAH");

        btnMin.setText("-");
        btnMin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinActionPerformed(evt);
            }
        });

        tfJumlah.setEditable(false);
        tfJumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfJumlahActionPerformed(evt);
            }
        });

        btnPlus.setText("+");
        btnPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlusActionPerformed(evt);
            }
        });

        btnTotal.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 12)); // NOI18N
        btnTotal.setText("TOTAL");
        btnTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTotalActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("TOTAL");

        tfTotal.setEditable(false);

        jLabel9.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("CASH");

        tfCash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCashActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("KEMBALI");

        tfKembali.setEditable(false);

        btnReset.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 12)); // NOI18N
        btnReset.setText("RESET");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        cbChococips.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        cbChococips.setForeground(new java.awt.Color(255, 255, 255));
        cbChococips.setText("Chococips - Rp. 3.000");
        cbChococips.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbChococipsActionPerformed(evt);
            }
        });

        cbChocoCrunch.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        cbChocoCrunch.setForeground(new java.awt.Color(255, 255, 255));
        cbChocoCrunch.setText("Choco Crunch - Rp. 3.500");
        cbChocoCrunch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbChocoCrunchActionPerformed(evt);
            }
        });

        cbStrawberry.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        cbStrawberry.setForeground(new java.awt.Color(255, 255, 255));
        cbStrawberry.setText("Strawberry - Rp. 4.000");
        cbStrawberry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbStrawberryActionPerformed(evt);
            }
        });

        cbKeju.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        cbKeju.setForeground(new java.awt.Color(255, 255, 255));
        cbKeju.setText("Keju - Rp. 3.500");
        cbKeju.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbKejuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(123, 123, 123))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                            .addComponent(rbChocoCheese)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(rbPillowCokelat))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(rbFlossRoll)
                                                .addComponent(rbAbonRoll))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(rbEggBun)
                                                .addComponent(rbChickenFloss))))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(4, 4, 4)
                                        .addComponent(btnMin, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(tfJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnPlus, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(48, 48, 48)
                                        .addComponent(btnTotal))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(tfCash, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(82, 82, 82)
                                .addComponent(jLabel7)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(tfTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(jLabel8)
                                            .addGap(45, 45, 45)))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbStrawberry)
                                    .addComponent(cbChocoCrunch)
                                    .addComponent(cbKeju)
                                    .addComponent(cbChococips))
                                .addGap(39, 39, 39))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(jLabel5)
                        .addGap(202, 202, 202)
                        .addComponent(jLabel6))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(254, 254, 254)
                        .addComponent(btnReset)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbChocoCheese)
                    .addComponent(rbPillowCokelat)
                    .addComponent(cbChococips))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbFlossRoll)
                    .addComponent(rbChickenFloss)
                    .addComponent(cbChocoCrunch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbAbonRoll)
                    .addComponent(rbEggBun)
                    .addComponent(cbStrawberry))
                .addGap(5, 5, 5)
                .addComponent(cbKeju)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMin)
                    .addComponent(tfJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPlus)
                    .addComponent(btnTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfCash, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfKembali, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnReset)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 119, 610, 340));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void tfJumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfJumlahActionPerformed
        try {
            quantity = Integer.parseInt(tfJumlah.getText());
            updateTotal();
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Invalid quantity input!");
        }
    }//GEN-LAST:event_tfJumlahActionPerformed

    private void btnTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTotalActionPerformed
        // pengguna sudah memilih roti tetapi belum memilih jumlah (quantity masih 0)
        if (breadPrice > 0 && quantity == 0) {
            JOptionPane.showMessageDialog(this, "Mohon pilih jumlah pesanan!", "Jumlah Kosong", JOptionPane.WARNING_MESSAGE);
        }
        // belum ada roti yang dipilih atau topping yang dipilih
        else if (quantity == 0 || (breadPrice == 0 && toppingPrice == 0)) {
            JOptionPane.showMessageDialog(this, "Silakan pilih menu roti dan topping terlebih dahulu!", "Pesanan Kosong", JOptionPane.WARNING_MESSAGE);
        } else {
            updateTotal();
        }
    }//GEN-LAST:event_btnTotalActionPerformed

    private void btnMinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinActionPerformed
        // Kurangi jumlah pesanan, jika lebih dari 0
        if (quantity > 0) {
            quantity--;
        }
        // Tampilkan jumlah pesanan di tfJumlah
        tfJumlah.setText(String.valueOf(quantity));
    }//GEN-LAST:event_btnMinActionPerformed

    private void rbChocoCheeseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbChocoCheeseActionPerformed
        updateBreadPrice(20500);
    }//GEN-LAST:event_rbChocoCheeseActionPerformed

    private void rbFlossRollActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbFlossRollActionPerformed
        updateBreadPrice(10500);
    }//GEN-LAST:event_rbFlossRollActionPerformed

    private void rbAbonRollActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbAbonRollActionPerformed
        updateBreadPrice(22000);
    }//GEN-LAST:event_rbAbonRollActionPerformed

    private void rbPillowCokelatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbPillowCokelatActionPerformed
        updateBreadPrice(20000);
    }//GEN-LAST:event_rbPillowCokelatActionPerformed

    private void rbChickenFlossActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbChickenFlossActionPerformed
        updateBreadPrice(15000);
    }//GEN-LAST:event_rbChickenFlossActionPerformed

    private void rbEggBunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbEggBunActionPerformed
        updateBreadPrice(13000);
    }//GEN-LAST:event_rbEggBunActionPerformed

    private void tfCashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCashActionPerformed
        calculateChange();
    }//GEN-LAST:event_tfCashActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        resetForm();
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlusActionPerformed
        // Tambah jumlah pesanan
        quantity++;
        // Tampilkan jumlah pesanan di tfJumlah
        tfJumlah.setText(String.valueOf(quantity));
    }//GEN-LAST:event_btnPlusActionPerformed

    private void cbStrawberryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbStrawberryActionPerformed
        updateToppingPrice(4000, cbStrawberry.isSelected());
    }//GEN-LAST:event_cbStrawberryActionPerformed

    private void cbChococipsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbChococipsActionPerformed
        updateToppingPrice(3000, cbChococips.isSelected());
    }//GEN-LAST:event_cbChococipsActionPerformed

    private void cbChocoCrunchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbChocoCrunchActionPerformed
        updateToppingPrice(3500, cbChocoCrunch.isSelected());
    }//GEN-LAST:event_cbChocoCrunchActionPerformed

    private void cbKejuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbKejuActionPerformed
        updateToppingPrice(3500, cbKeju.isSelected());
    }//GEN-LAST:event_cbKejuActionPerformed
 
    private void updateBreadPrice(int price) {
        breadPrice = price;
        updateTotal();
    }
    
    private void updateToppingPrice(int toppingPrice, boolean isSelected) {
        if (isSelected) {
            totalToppingPrice += toppingPrice;
        } else {
            totalToppingPrice -= toppingPrice;
        }
        updateTotal();
    }
    
    private void updateTotal() {
        // Hitung total harga sebelum diskon
        total = (breadPrice + totalToppingPrice) * quantity;
        
        // Jika total lebih dari 100.000, terapkan diskon 5%
        if (total > 100000) {
            double diskon = total * 0.05;  // 5% dari total
            total = (int) (total - diskon);  // Kurangi total dengan diskon
            JOptionPane.showMessageDialog(this, "Selamat! Anda mendapatkan diskon 5% pada pembelian ini.");
        }

        // Tampilkan total setelah diskon (jika ada) ke dalam tfTotal
        tfTotal.setText(String.valueOf(total));

    }

    
    private void resetForm() {
        quantity = 0;
        total = 0;
        breadPrice = 0;
        toppingPrice = 0;
        totalToppingPrice = 0;
        
        ButtonGroup breadGroup = new ButtonGroup();
        breadGroup.add(rbChocoCheese);
        breadGroup.add(rbFlossRoll);
        breadGroup.add(rbAbonRoll);
        breadGroup.add(rbPillowCokelat);
        breadGroup.add(rbChickenFloss);
        breadGroup.add(rbEggBun);
        breadGroup.clearSelection();

        cbChococips.setSelected(false);
        cbChocoCrunch.setSelected(false);
        cbStrawberry.setSelected(false);
        cbKeju.setSelected(false);


        tfJumlah.setText("0");
        tfTotal.setText("0");
        tfCash.setText("");
        tfKembali.setText("");
    }
    
    private void calculateChange() {
        try {
            int cash = Integer.parseInt(tfCash.getText());
            int change = cash - total;
            if (change >= 0) {
                tfKembali.setText(String.valueOf(change));
            } else {
                JOptionPane.showMessageDialog(this, "Insufficient cash!");
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Invalid cash input!");
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PemesanannRoti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PemesanannRoti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PemesanannRoti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PemesanannRoti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PemesanannRoti().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btgrpMenu;
    private javax.swing.ButtonGroup btgrpTopping;
    private javax.swing.JButton btnMin;
    private javax.swing.JButton btnPlus;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnTotal;
    private javax.swing.JCheckBox cbChocoCrunch;
    private javax.swing.JCheckBox cbChococips;
    private javax.swing.JCheckBox cbKeju;
    private javax.swing.JCheckBox cbStrawberry;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton rbAbonRoll;
    private javax.swing.JRadioButton rbChickenFloss;
    private javax.swing.JRadioButton rbChocoCheese;
    private javax.swing.JRadioButton rbEggBun;
    private javax.swing.JRadioButton rbFlossRoll;
    private javax.swing.JRadioButton rbPillowCokelat;
    private javax.swing.JTextField tfCash;
    private javax.swing.JTextField tfJumlah;
    private javax.swing.JTextField tfKembali;
    private javax.swing.JTextField tfTotal;
    // End of variables declaration//GEN-END:variables
}
