/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package modul4_lanny;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Random;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author lanny aprilia
 */
public class tebakangka_lanny extends javax.swing.JFrame {

    /**
     * Creates new form tebakangka_lanny
     */
    public tebakangka_lanny() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        resetGame();
        
        historyModel = new DefaultListModel<>();
        listscore.setModel(historyModel);

        
        btnreset.addActionListener(new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            resetGame(); 
        }
        });
        
        btntebak.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                playGame();
            }
        });
    }
    
    private int target;
    private int score = 100;
    private DefaultListModel<String> historyModel;

    
    private void resetGame() {
        target = new Random().nextInt(100) + 1; 
        score = 100;
        txtscore.setText(String.valueOf(score));
        txthasil.setText("");
        txtangka.setText("");
        btntebak.setText("   Tebak (10)");
        txtangka.setEditable(true);
        btntebak.setEnabled(true);
}
    
    private void playGame() {
        try {
            int tebakan = Integer.parseInt(txtangka.getText());
            if (tebakan < 1 || tebakan > 100) {
                txthasil.setText("Masukkan angka 1 - 100");
                return;
            }
            
            if (tebakan < target) {
                txthasil.setText("Aku Lebih Besar dari " + tebakan);
                score -= 10;
            } else if (tebakan > target) {
                txthasil.setText("Aku Lebih Kecil dari " + tebakan);
                score -= 10;
            } else {
                txthasil.setText("Tebakan Benar! Angka " + tebakan);
                JOptionPane.showMessageDialog(null, "Anda Berhasil!");

                String nama = JOptionPane.showInputDialog("Masukkan Nama Anda:");
                while (nama == null || nama.trim().isEmpty()) {
                    JOptionPane.showMessageDialog(null, "Anda harus memasukkan nama!", "Peringatan", JOptionPane.WARNING_MESSAGE);
                    nama = JOptionPane.showInputDialog("Masukkan Nama Anda:");
                }
                
                String isihistory = nama + " - Score : " + score;
                historyModel.addElement(isihistory);
//                txascore.append("|  " +nama + " - Score: " + score + "\n");
                txtangka.setEditable(false);
                btntebak.setEnabled(false);
                return;
                
            }
            
            txtscore.setText(String.valueOf(score));
            
            int buttontebakan = score / 10;
            btntebak.setText("   Tebak ( " + buttontebakan + " )");
            
            if (score <= 0) {
                txthasil.setText("Anda Gagal! Kesempatan Habis.");
                JOptionPane.showMessageDialog(null, "Anda Gagal! Permainan akan di mulai ulang", "Game Over", JOptionPane.INFORMATION_MESSAGE);
                resetGame(); 
            }
        } catch (NumberFormatException ex) {
            txthasil.setText("Masukkan angka yang valid!");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtangka = new javax.swing.JTextField();
        txthasil = new javax.swing.JTextField();
        txtscore = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        btntebak = new javax.swing.JButton();
        btnreset = new javax.swing.JButton();
        btnkeluar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listscore = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setBackground(new java.awt.Color(255, 102, 51));

        jPanel1.setBackground(new java.awt.Color(255, 204, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 228, 225));
        jPanel3.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Script MT Bold", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 0));
        jLabel1.setText("Let's Play The Game");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 290, 49));

        jLabel2.setFont(new java.awt.Font("Imprint MT Shadow", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 0, 0));
        jLabel2.setText("~ Ayo Main Tebak Angka ~");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 260, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 100));

        jPanel5.setBackground(new java.awt.Color(255, 153, 153));
        jPanel5.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 204, 204));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Script MT Bold", 0, 18)); // NOI18N
        jLabel3.setText("Score");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 140, -1));

        jLabel4.setFont(new java.awt.Font("Script MT Bold", 0, 18)); // NOI18N
        jLabel4.setText("Masukkan Angka");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 140, -1));

        jLabel5.setFont(new java.awt.Font("Script MT Bold", 0, 18)); // NOI18N
        jLabel5.setText("Hasil");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 140, -1));

        txtangka.setBackground(new java.awt.Color(255, 228, 225));
        jPanel4.add(txtangka, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, 320, -1));

        txthasil.setEditable(false);
        txthasil.setBackground(new java.awt.Color(255, 228, 225));
        jPanel4.add(txthasil, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 320, -1));

        txtscore.setEditable(false);
        txtscore.setBackground(new java.awt.Color(255, 228, 225));
        jPanel4.add(txtscore, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, 320, -1));

        jLabel6.setText(":");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 40, -1));

        jLabel7.setText(":");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, 40, -1));

        jLabel8.setText(":");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 40, -1));

        jPanel5.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 600, 190));

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\lanny aprilia\\Downloads\\labubu2.png")); // NOI18N
        jPanel5.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, -1, -1));

        jPanel9.setBackground(new java.awt.Color(255, 153, 153));
        jPanel9.setLayout(new java.awt.GridBagLayout());

        btntebak.setBackground(new java.awt.Color(255, 228, 225));
        btntebak.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btntebak.setIcon(new javax.swing.ImageIcon("C:\\Users\\lanny aprilia\\Downloads\\lbb6.png")); // NOI18N
        btntebak.setText("   Tebak ( 10 )");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.insets = new java.awt.Insets(24, 15, 0, 19);
        jPanel9.add(btntebak, gridBagConstraints);

        btnreset.setBackground(new java.awt.Color(255, 228, 225));
        btnreset.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnreset.setIcon(new javax.swing.ImageIcon("C:\\Users\\lanny aprilia\\Downloads\\lbb3.png")); // NOI18N
        btnreset.setText("   Reset");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(24, 0, 0, 20);
        jPanel9.add(btnreset, gridBagConstraints);

        btnkeluar.setBackground(new java.awt.Color(255, 228, 225));
        btnkeluar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnkeluar.setIcon(new javax.swing.ImageIcon("C:\\Users\\lanny aprilia\\Downloads\\lbb7.png")); // NOI18N
        btnkeluar.setText("   Keluar");
        btnkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkeluarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(24, 0, 0, 0);
        jPanel9.add(btnkeluar, gridBagConstraints);

        jPanel5.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, 390, -1));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 660, 360));

        jTabbedPane1.addTab("Game Play", jPanel1);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(255, 204, 255));

        jLabel12.setFont(new java.awt.Font("Script MT Bold", 1, 30)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(153, 0, 0));
        jLabel12.setText("Score History");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(197, Short.MAX_VALUE)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(186, 186, 186))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 570, 60));

        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\lanny aprilia\\Downloads\\lbb.png")); // NOI18N
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        jPanel7.setBackground(new java.awt.Color(255, 102, 204));
        jPanel7.setForeground(new java.awt.Color(255, 102, 204));

        jScrollPane2.setViewportView(listscore);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 509, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 570, 300));

        jTabbedPane1.addTab("Score", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkeluarActionPerformed
        int keluar = JOptionPane.showConfirmDialog(null,"Anda yakin ingin keluar permainan?","Keluar",JOptionPane.YES_NO_OPTION);
        if (keluar == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_btnkeluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tebakangka_lanny.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tebakangka_lanny.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tebakangka_lanny.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tebakangka_lanny.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tebakangka_lanny().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnkeluar;
    private javax.swing.JButton btnreset;
    private javax.swing.JButton btntebak;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JList<String> listscore;
    private javax.swing.JTextField txtangka;
    private javax.swing.JTextField txthasil;
    private javax.swing.JTextField txtscore;
    // End of variables declaration//GEN-END:variables
}
