/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package modul3;

import javax.swing.JOptionPane;

/**
 *
 * @author faza
 */
public class Apotek extends javax.swing.JFrame {

    /**
     * Creates new form Apotek
     */
    int totalHarga;
    public Apotek() {
        initComponents();
    }
    
    // Fungsi untuk memperbarui total harga
    private void updateTotalHarga() {
        totalHarga = 0; // Reset total harga

        // Tambah harga obat jika checkbox tercentang
        if (Paracetamol.isSelected()) totalHarga += 5000;
        if (IbuProfen.isSelected()) totalHarga += 7000;
        if (Panadol.isSelected()) totalHarga += 8000;
        if (Bodrex.isSelected()) totalHarga += 6000;
        if (Mixagrip.isSelected()) totalHarga += 5000;
        if (Neozep.isSelected()) totalHarga += 6500;
        if (OBHCombi.isSelected()) totalHarga += 5500;
        if (Siladex.isSelected()) totalHarga += 6000;
        if (Promag.isSelected()) totalHarga += 4500;
        if (Mylanta.isSelected()) totalHarga += 5000;

        // Tampilkan total harga di kolom yang sesuai
        totalHargaField.setText("Rp " + totalHarga);
    }
    
    private void clearAllCheckboxes() {
        Paracetamol.setSelected(false);
        IbuProfen.setSelected(false);
        Panadol.setSelected(false);
        Bodrex.setSelected(false);
        Mixagrip.setSelected(false);
        Neozep.setSelected(false);
        OBHCombi.setSelected(false);
        Siladex.setSelected(false);
        Promag.setSelected(false);
        Mylanta.setSelected(false);
    }
    // Metode untuk menampilkan detail obat
    private void showDetail(String obatName) {
            String detail = "";

    switch (obatName) {
        case "Paracetamol":
            detail = "Paracetamol:\n- Dosis: Dewasa 500 mg setiap 4-6 jam\n- Indikasi: Menurunkan demam, mengurangi nyeri\n- Efek samping: Mual, reaksi alergi, sakit perut";
            break;
        case "Mixagrip":
            detail = "Mixagrip:\n- Dosis: Dewasa 1 tablet setiap 8 jam\n- Indikasi: Mengatasi flu, pilek, dan demam\n- Efek samping: Mengantuk, pusing, mulut kering";
            break;
        case "OBH Combi":
            detail = "OBH Combi:\n- Dosis: Dewasa 1 sendok makan setiap 4 jam\n- Indikasi: Meredakan batuk berdahak\n- Efek samping: Mengantuk, mual";
            break;
        case "Panadol":
            detail = "Panadol:\n- Dosis: Dewasa 500 mg setiap 4-6 jam\n- Indikasi: Mengurangi nyeri, demam\n- Efek samping: Mual, reaksi alergi, sakit perut";
            break;
        case "Promag":
            detail = "Promag:\n- Dosis: 1-2 tablet sebelum makan\n- Indikasi: Mengatasi asam lambung dan maag\n- Efek samping: Mengantuk, sembelit, mual";
            break;
        case "Mylanta":
            detail = "Mylanta:\n- Dosis: Dewasa 1-2 sendok makan setelah makan\n- Indikasi: Meredakan sakit maag dan asam lambung\n- Efek samping: Diare atau sembelit";
            break;
        case "Siladex":
            detail = "Siladex:\n- Dosis: Dewasa 1 sendok makan setiap 4 jam\n- Indikasi: Meredakan batuk tidak berdahak\n- Efek samping: Mengantuk, pusing";
            break;
        case "NeoZep":
            detail = "NeoZep:\n- Dosis: Dewasa 1 tablet setiap 8 jam\n- Indikasi: Mengatasi flu dan pilek\n- Efek samping: Mengantuk, pusing, mulut kering";
            break;
        case "Bodrex":
            detail = "Bodrex:\n- Dosis: Dewasa 1-2 tablet setiap 6 jam\n- Indikasi: Meredakan sakit kepala, demam, nyeri otot\n- Efek samping: Mengantuk, mual, sakit perut";
            break;
        case "IbuProfen":
            detail = "IbuProfen:\n- Dosis: Dewasa 200-400 mg setiap 4-6 jam\n- Indikasi: Meredakan nyeri ringan hingga sedang, inflamasi\n- Efek samping: Mual, sakit perut, pusing";
            break;
        default:
            detail = "Detail tidak tersedia.";
            break;
    }

    // Tampilkan detail menggunakan JOptionPane
    javax.swing.JOptionPane.showMessageDialog(this, detail, "Detail " + obatName, javax.swing.JOptionPane.INFORMATION_MESSAGE);
 
   
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        Paracetamol = new javax.swing.JCheckBox();
        Mixagrip = new javax.swing.JCheckBox();
        OBHCombi = new javax.swing.JCheckBox();
        Panadol = new javax.swing.JCheckBox();
        Promag = new javax.swing.JCheckBox();
        Mylanta = new javax.swing.JCheckBox();
        Siladex = new javax.swing.JCheckBox();
        Neozep = new javax.swing.JCheckBox();
        Bodrex = new javax.swing.JCheckBox();
        IbuProfen = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        NamaPemesanField = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        totalHargaField = new javax.swing.JTextField();
        BtnBuatPesanan = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(84, 195, 146));
        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Cooper Black", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("APOTEK TUTUP GAK ADA OBAT");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(140, 0, 770, 60);

        jLabel2.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Jl. Jalan Ke Kota Batu, Cakep ");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(260, 20, 770, 60);

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 60));

        jPanel1.setBackground(new java.awt.Color(21, 179, 146));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(115, 236, 139));
        jPanel3.setLayout(new java.awt.GridBagLayout());

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Daftar Obat");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        jPanel3.add(jLabel4, gridBagConstraints);

        Paracetamol.setText("Paracetamol");
        Paracetamol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ParacetamolActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        jPanel3.add(Paracetamol, gridBagConstraints);

        Mixagrip.setText("Mixagrip");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        jPanel3.add(Mixagrip, gridBagConstraints);

        OBHCombi.setText("OBH Combi");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        jPanel3.add(OBHCombi, gridBagConstraints);

        Panadol.setText("Panadol");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel3.add(Panadol, gridBagConstraints);

        Promag.setText("Promag");
        Promag.setToolTipText("");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel3.add(Promag, gridBagConstraints);

        Mylanta.setText("Mylanta");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        jPanel3.add(Mylanta, gridBagConstraints);

        Siladex.setText("Siladex");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        jPanel3.add(Siladex, gridBagConstraints);

        Neozep.setText("Neozep");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        jPanel3.add(Neozep, gridBagConstraints);

        Bodrex.setText("Bodrex");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel3.add(Bodrex, gridBagConstraints);

        IbuProfen.setText("IbuProfen");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel3.add(IbuProfen, gridBagConstraints);

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\faza\\Downloads\\Video\\Paracetamol.png")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.ipady = 10;
        jPanel3.add(jLabel5, gridBagConstraints);

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\faza\\Downloads\\Video\\mixagrip.png")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.ipady = 10;
        jPanel3.add(jLabel6, gridBagConstraints);

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\faza\\Downloads\\Video\\obh.png")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.ipady = 10;
        jPanel3.add(jLabel7, gridBagConstraints);

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\faza\\Downloads\\Video\\panadol.png")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.ipady = 10;
        jPanel3.add(jLabel8, gridBagConstraints);

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\faza\\Downloads\\Video\\promag.png")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.ipady = 10;
        jPanel3.add(jLabel9, gridBagConstraints);

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\faza\\Downloads\\Video\\mylanta.png")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.ipady = 10;
        jPanel3.add(jLabel10, gridBagConstraints);

        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\faza\\Downloads\\Video\\siladex.png")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.ipady = 10;
        jPanel3.add(jLabel11, gridBagConstraints);

        jLabel12.setIcon(new javax.swing.ImageIcon("C:\\Users\\faza\\Downloads\\Video\\neozep.png")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.ipady = 10;
        jPanel3.add(jLabel12, gridBagConstraints);

        jLabel13.setIcon(new javax.swing.ImageIcon("C:\\Users\\faza\\Downloads\\Video\\bodrex.png")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.ipady = 10;
        jPanel3.add(jLabel13, gridBagConstraints);

        jLabel14.setIcon(new javax.swing.ImageIcon("C:\\Users\\faza\\Downloads\\Video\\ibuprofen.png")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.ipady = 10;
        jPanel3.add(jLabel14, gridBagConstraints);

        jButton1.setText("Detail");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        jPanel3.add(jButton1, gridBagConstraints);

        jButton2.setText("Detail");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        jPanel3.add(jButton2, gridBagConstraints);

        jButton3.setText("Detail");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        jPanel3.add(jButton3, gridBagConstraints);

        jButton4.setText("Detail");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        jPanel3.add(jButton4, gridBagConstraints);

        jButton5.setText("Detail");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 3;
        jPanel3.add(jButton5, gridBagConstraints);

        jButton6.setText("Detail");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        jPanel3.add(jButton6, gridBagConstraints);

        jButton7.setText("Detail");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        jPanel3.add(jButton7, gridBagConstraints);

        jButton8.setText("Detail");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        jPanel3.add(jButton8, gridBagConstraints);

        jButton9.setText("Detail");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 6;
        jPanel3.add(jButton9, gridBagConstraints);

        jButton10.setText("Detail");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 6;
        jPanel3.add(jButton10, gridBagConstraints);

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 368));

        jPanel4.setBackground(new java.awt.Color(210, 255, 114));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(210, 255, 114));

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jLabel3.setText("Pembayaran");
        jPanel6.add(jLabel3);

        jPanel4.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 70));

        jPanel5.setBackground(new java.awt.Color(210, 255, 114));
        jPanel5.setLayout(new java.awt.GridLayout(2, 2));

        jLabel15.setText("Nama Pemesan");
        jPanel5.add(jLabel15);
        jPanel5.add(NamaPemesanField);

        jLabel16.setText("Total Harga");
        jPanel5.add(jLabel16);

        totalHargaField.setEditable(false);
        totalHargaField.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                totalHargaFieldMouseMoved(evt);
            }
        });
        jPanel5.add(totalHargaField);

        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 190, 70));

        BtnBuatPesanan.setText("Buat Pesanan");
        BtnBuatPesanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBuatPesananActionPerformed(evt);
            }
        });
        jPanel4.add(BtnBuatPesanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, -1, -1));

        jLabel17.setText("Apa Gejala Anda?");
        jPanel4.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Demam", "Sakit Kepala", "Pilek", "Batuk", "Sakit Perut" }));
        jComboBox1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jComboBox1FocusGained(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel4.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, -1, -1));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 0, 190, 370));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 1010, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ParacetamolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ParacetamolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ParacetamolActionPerformed

    private void jComboBox1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jComboBox1FocusGained
        // TODO add your handling code here:
        jComboBox1.removeItem("===Pilih===");
    }//GEN-LAST:event_jComboBox1FocusGained

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        String gejala = (String) jComboBox1.getSelectedItem();
        String rekomendasiObat = "";
        totalHarga = 0;
        clearAllCheckboxes();
    // Tentukan rekomendasi obat berdasarkan gejala
    switch (gejala) {
        case "Demam":
            rekomendasiObat = "Rekomendasi Obat:\n- Paracetamol\n- Ibuprofen";
            Paracetamol.setSelected(true);
            IbuProfen.setSelected(true);
            break;
        case "Sakit Kepala":
            rekomendasiObat = "Rekomendasi Obat:\n- Paracetamol\n- Panadol\n- Bodrex";
            Paracetamol.setSelected(true);
            Panadol.setSelected(true);
            Bodrex.setSelected(true);
            break;
        case "Pilek":
            rekomendasiObat = "Rekomendasi Obat:\n- Mixagrip\n- Neozep";
            Mixagrip.setSelected(true);
            Neozep.setSelected(true);
            break;
        case "Batuk":
            rekomendasiObat = "Rekomendasi Obat:\n- OBH Combi\n- Siladex";
            OBHCombi.setSelected(true);
            Siladex.setSelected(true);
            break;
        case "Sakit Perut":
            rekomendasiObat = "Rekomendasi Obat:\n- Promag\n- Mylanta";
            Promag.setSelected(true);
            Mylanta.setSelected(true);
            break;
        default:
            rekomendasiObat = "Silakan pilih gejala untuk melihat rekomendasi obat.";
            break;
    }
    updateTotalHarga();
    // Tampilkan rekomendasi obat dalam dialog
    JOptionPane.showMessageDialog(this, rekomendasiObat, "Rekomendasi Obat", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void totalHargaFieldMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_totalHargaFieldMouseMoved
        // TODO add your handling code here:
        updateTotalHarga();
    }//GEN-LAST:event_totalHargaFieldMouseMoved

    private void BtnBuatPesananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBuatPesananActionPerformed
        // TODO add your handling code here:
        // Ambil data dari input
        String namaPemesan = NamaPemesanField.getText();
        String gejala = (String) jComboBox1.getSelectedItem();
        String obatDipilih = ""; // Untuk menyimpan daftar obat yang dipilih
        int totalHarga = 0;

        // Cek jika nama pemesan kosong
        if (namaPemesan.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nama pemesan tidak boleh kosong!", "Error", JOptionPane.ERROR_MESSAGE);
            return; // Menghentikan eksekusi jika nama kosong
        }

        // Ambil obat yang dipilih
        if (Paracetamol.isSelected()) {
            obatDipilih += "Paracetamol, ";
            totalHarga += 5000;
        }
        if (IbuProfen.isSelected()) {
            obatDipilih += "Ibuprofen, ";
            totalHarga += 7000;
        }
        if (Panadol.isSelected()) {
            obatDipilih += "Panadol, ";
            totalHarga += 8000;
        }
        if (Bodrex.isSelected()) {
            obatDipilih += "Bodrex, ";
            totalHarga += 6000;
        }
        if (Mixagrip.isSelected()) {
            obatDipilih += "Mixagrip, ";
            totalHarga += 5000;
        }
        if (Neozep.isSelected()) {
            obatDipilih += "Neozep, ";
            totalHarga += 6500;
        }
        if (OBHCombi.isSelected()) {
            obatDipilih += "OBH Combi, ";
            totalHarga += 5500;
        }
        if (Siladex.isSelected()) {
            obatDipilih += "Siladex, ";
            totalHarga += 6000;
        }
        if (Promag.isSelected()) {
            obatDipilih += "Promag, ";
            totalHarga += 4500;
        }
        if (Mylanta.isSelected()) {
            obatDipilih += "Mylanta, ";
            totalHarga += 5000;
        }

        // Hapus koma terakhir jika ada
        if (!obatDipilih.isEmpty()) {
            obatDipilih = obatDipilih.substring(0, obatDipilih.length() - 2);
        } else {
            JOptionPane.showMessageDialog(this, "Pilih setidaknya satu obat!", "Error", JOptionPane.ERROR_MESSAGE);
            return; // Menghentikan eksekusi jika tidak ada obat yang dipilih
        }

        // Tampilkan konfirmasi pesanan
        String pesan = "Pesanan Anda:\n"
                + "Nama Pemesan: " + namaPemesan + "\n"
                + "Gejala: " + gejala + "\n"
                + "Obat yang Dipilih: " + obatDipilih + "\n"
                + "Total Harga: Rp " + totalHarga;

        JOptionPane.showMessageDialog(this, pesan, "Pesanan Berhasil", JOptionPane.INFORMATION_MESSAGE);
        clearAllCheckboxes();
        NamaPemesanField.setText("");
        totalHargaField.setText("");
    }//GEN-LAST:event_BtnBuatPesananActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        showDetail("Paracetamol");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        showDetail("Mixagrip");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        showDetail("OBH Combi");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        showDetail("Panadol");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        showDetail("Promag");
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        showDetail("Mylanta");
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        showDetail("Siladex");
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        showDetail("Neozep");
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        showDetail("Bodrex");
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        showDetail("IbuProfen");
    }//GEN-LAST:event_jButton10ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Apotek.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Apotek.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Apotek.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Apotek.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Apotek().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox Bodrex;
    private javax.swing.JButton BtnBuatPesanan;
    private javax.swing.JCheckBox IbuProfen;
    private javax.swing.JCheckBox Mixagrip;
    private javax.swing.JCheckBox Mylanta;
    private javax.swing.JTextField NamaPemesanField;
    private javax.swing.JCheckBox Neozep;
    private javax.swing.JCheckBox OBHCombi;
    private javax.swing.JCheckBox Panadol;
    private javax.swing.JCheckBox Paracetamol;
    private javax.swing.JCheckBox Promag;
    private javax.swing.JCheckBox Siladex;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTextField totalHargaField;
    // End of variables declaration//GEN-END:variables
}
