/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Citra
 */
public class Apotek extends javax.swing.JFrame { 
    
    private String[] namaObat;
    private String[] deskripsiObat;
    
    public Apotek() {
    initComponents();
    
    namaObat = new String[]{"Paracetamol", "Ibuprofen", "Antibiotik", "Longatin", "Antivirus",
                            "Sanadryl Ekspektoran Sirup", "Prome Sirup", "Comtusi", "Panadol 500 mg", "Procold"};
    deskripsiObat = new String[]{
                "Mengatasi demam dan nyeri ringan", //0
                "Anti-inflamasi untuk nyeri dan demam", //1
                "Antibiotik untuk infeksi bakteri", //2
                "Mengatasi gejala batuk kering pada kondisi flu dan batuk", //3
                "Obat antivirus pada kasus infeksi virus yang berat", //4
                "Mengatasi nyeri pada otot", //5
                "Mengatasi batuk, terutama yang disebabkan oleh alergi", //6
                "Mengatasi flu dan batuk yang disertai batuk berdahak", //7
                "Meredakan demam dan nyeri otot yang mungkin muncul akibat flu", //8
                "Mengatasi gejala flu, seperti demam, sakit kepala, hidung tersumbat" //9
        };
    }

 private void tampilkanObat(String gejala, String[] namaObat, String[] deskripsiObat) {
        switch (gejala) {
            case "Pusing":
                NamaObat.setText("Nama Obat : " + namaObat[9] + " dan " + namaObat[1]);
                Deskripsi.setText("Deskripsi : " + deskripsiObat[9] + " dan " + deskripsiObat[4]);
                break;
            case "Batuk":
                NamaObat.setText("Nama Obat : " + namaObat[6] + " dan " + namaObat[7]);
                Deskripsi.setText("Deskripsi : " + deskripsiObat[6] + " dan " + deskripsiObat[7]);
                break;
            case "Demam":
                NamaObat.setText("Nama Obat : " + namaObat[0] + " dan " + namaObat[1]);
                Deskripsi.setText("Deskripsi : " + deskripsiObat[0] + " dan " + deskripsiObat[1]);
                break;
            case "Flu":
                NamaObat.setText("Nama Obat : " + namaObat[2] + " dan " + namaObat[3]);
                Deskripsi.setText("Deskripsi : " + deskripsiObat[2] + " dan " + deskripsiObat[3]);
                break;
            case "Nyeri Otot":
                NamaObat.setText("Nama Obat : " + namaObat[0] + " dan " + namaObat[8]);
                Deskripsi.setText("Deskripsi : " + deskripsiObat[8] + " dan " + deskripsiObat[5]);
                break;
            default:
                NamaObat.setText("Nama Obat:... ");
                Deskripsi.setText("Deskripsi:... ");
                break;
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        paneltombol = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        Pusing = new javax.swing.JButton();
        Batuk = new javax.swing.JButton();
        Demam = new javax.swing.JButton();
        Flu = new javax.swing.JButton();
        Nyeriotot = new javax.swing.JButton();
        paneldeskripsi = new javax.swing.JPanel();
        LabelGaris2 = new javax.swing.JLabel();
        NamaObat = new javax.swing.JLabel();
        Deskripsi = new javax.swing.JLabel();
        LabelGaris3 = new javax.swing.JLabel();
        panelgambar = new javax.swing.JPanel();
        Paracetamol = new javax.swing.JLabel();
        Ibuprofen = new javax.swing.JLabel();
        Antibiotik = new javax.swing.JLabel();
        Longatin = new javax.swing.JLabel();
        Antivirus = new javax.swing.JLabel();
        Sirup = new javax.swing.JLabel();
        PromeSirup = new javax.swing.JLabel();
        Comtusi = new javax.swing.JLabel();
        Panadol = new javax.swing.JLabel();
        Procold = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(790, 489));
        setResizable(false);

        paneltombol.setBackground(new java.awt.Color(255, 0, 51));
        paneltombol.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel1.setText("APOTEK SEHATKU");
        paneltombol.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, -1, 30));

        jLabel2.setText("Jl. Bandeng - Jabon, Sidoarjo Jawa Timur");
        paneltombol.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, -1, -1));

        jLabel4.setText("--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------");
        paneltombol.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, -1, 30));

        jPanel1.setBackground(new java.awt.Color(255, 0, 51));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Pilihan Sakit :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(0, 21, 0, 21);
        jPanel1.add(jLabel3, gridBagConstraints);

        Pusing.setText("Pusing");
        Pusing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PusingActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(12, 0, 12, 0);
        jPanel1.add(Pusing, gridBagConstraints);

        Batuk.setText("Batuk");
        Batuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BatukActionPerformed(evt);
            }
        });
        jPanel1.add(Batuk, new java.awt.GridBagConstraints());

        Demam.setText("Demam");
        Demam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DemamActionPerformed(evt);
            }
        });
        jPanel1.add(Demam, new java.awt.GridBagConstraints());

        Flu.setText("Flu");
        Flu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FluActionPerformed(evt);
            }
        });
        jPanel1.add(Flu, new java.awt.GridBagConstraints());

        Nyeriotot.setText("Nyeri Otot");
        Nyeriotot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NyeriototActionPerformed(evt);
            }
        });
        jPanel1.add(Nyeriotot, new java.awt.GridBagConstraints());

        paneltombol.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 500, 97));

        getContentPane().add(paneltombol, java.awt.BorderLayout.PAGE_START);

        paneldeskripsi.setBackground(new java.awt.Color(255, 255, 255));

        LabelGaris2.setText("--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------");

        NamaObat.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        NamaObat.setText("Nama Obat :");

        Deskripsi.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Deskripsi.setText("Deskripsi :");

        LabelGaris3.setText("--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------");

        javax.swing.GroupLayout paneldeskripsiLayout = new javax.swing.GroupLayout(paneldeskripsi);
        paneldeskripsi.setLayout(paneldeskripsiLayout);
        paneldeskripsiLayout.setHorizontalGroup(
            paneldeskripsiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(NamaObat)
            .addComponent(Deskripsi)
            .addComponent(LabelGaris2, javax.swing.GroupLayout.PREFERRED_SIZE, 926, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(LabelGaris3, javax.swing.GroupLayout.PREFERRED_SIZE, 952, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        paneldeskripsiLayout.setVerticalGroup(
            paneldeskripsiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneldeskripsiLayout.createSequentialGroup()
                .addComponent(LabelGaris2)
                .addGap(0, 0, 0)
                .addComponent(NamaObat)
                .addGap(0, 0, 0)
                .addComponent(Deskripsi)
                .addGap(0, 0, 0)
                .addComponent(LabelGaris3))
        );

        getContentPane().add(paneldeskripsi, java.awt.BorderLayout.PAGE_END);

        panelgambar.setBackground(new java.awt.Color(255, 255, 255));
        panelgambar.setLayout(new java.awt.GridLayout(2, 5));

        Paracetamol.setIcon(new javax.swing.ImageIcon(getClass().getResource("/paracetamol.png"))); // NOI18N
        Paracetamol.setText("Paracetamol");
        panelgambar.add(Paracetamol);

        Ibuprofen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ibuprofen.jpg"))); // NOI18N
        Ibuprofen.setText("Ibuprofen");
        panelgambar.add(Ibuprofen);

        Antibiotik.setIcon(new javax.swing.ImageIcon(getClass().getResource("/antibiotik.jpg"))); // NOI18N
        Antibiotik.setText("Antibiotik");
        panelgambar.add(Antibiotik);

        Longatin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/longatin.jpg"))); // NOI18N
        Longatin.setText("Longatin");
        panelgambar.add(Longatin);

        Antivirus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/antivirus.png"))); // NOI18N
        Antivirus.setText("Antivirus");
        panelgambar.add(Antivirus);

        Sirup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sanadryl Ekspektoran.png"))); // NOI18N
        Sirup.setText("Sanadryl Ekspektoran Sirup");
        panelgambar.add(Sirup);

        PromeSirup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prome sirup.png"))); // NOI18N
        PromeSirup.setText("Prome Sirup ");
        panelgambar.add(PromeSirup);

        Comtusi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/comtusi.png"))); // NOI18N
        Comtusi.setText("Comtusi");
        panelgambar.add(Comtusi);

        Panadol.setIcon(new javax.swing.ImageIcon(getClass().getResource("/panadol.png"))); // NOI18N
        Panadol.setText("Panadol 500 mg");
        panelgambar.add(Panadol);

        Procold.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proclod.png"))); // NOI18N
        Procold.setText("Procold");
        panelgambar.add(Procold);

        getContentPane().add(panelgambar, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PusingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PusingActionPerformed
        // TODO add your handling code here:
        tampilkanObat("Pusing", namaObat, deskripsiObat);
    }//GEN-LAST:event_PusingActionPerformed

    private void DemamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DemamActionPerformed
        // TODO add your handling code here:
        tampilkanObat("Demam", namaObat, deskripsiObat);
    }//GEN-LAST:event_DemamActionPerformed

    private void BatukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BatukActionPerformed
        // TODO add your handling code here:
        tampilkanObat("Batuk", namaObat, deskripsiObat);
    }//GEN-LAST:event_BatukActionPerformed

    private void FluActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FluActionPerformed
        // TODO add your handling code here:
        tampilkanObat("Flu", namaObat, deskripsiObat);
    }//GEN-LAST:event_FluActionPerformed

    private void NyeriototActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NyeriototActionPerformed
        // TODO add your handling code here:
        tampilkanObat("Nyeri Otot", namaObat, deskripsiObat);
    }//GEN-LAST:event_NyeriototActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Apotek.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Apotek.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Apotek.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Apotek.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Apotek().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Antibiotik;
    private javax.swing.JLabel Antivirus;
    private javax.swing.JButton Batuk;
    private javax.swing.JLabel Comtusi;
    private javax.swing.JButton Demam;
    private javax.swing.JLabel Deskripsi;
    private javax.swing.JButton Flu;
    private javax.swing.JLabel Ibuprofen;
    private javax.swing.JLabel LabelGaris2;
    private javax.swing.JLabel LabelGaris3;
    private javax.swing.JLabel Longatin;
    private javax.swing.JLabel NamaObat;
    private javax.swing.JButton Nyeriotot;
    private javax.swing.JLabel Panadol;
    private javax.swing.JLabel Paracetamol;
    private javax.swing.JLabel Procold;
    private javax.swing.JLabel PromeSirup;
    private javax.swing.JButton Pusing;
    private javax.swing.JLabel Sirup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel paneldeskripsi;
    private javax.swing.JPanel panelgambar;
    private javax.swing.JPanel paneltombol;
    // End of variables declaration//GEN-END:variables

}
