/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tokoroti;

import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
/**
 *
 * @author USEr
 */
public class TokoRotii extends javax.swing.JFrame {

    /**
     * Creates new form TokoRotii
     */
    public TokoRotii() {
        initComponents();
        
        tf_jumlah.setText("1");
        tf_jumlah.setEditable(false);
        tf_total.setEditable(false);
        tf_kembali.setEditable(false);
        btn_plus.setEnabled(false);
        btn_minus.setEnabled(false);
        
        tf_cash.getDocument().addDocumentListener(new DocumentListener() {
            public void changedUpdate(DocumentEvent e) {
                hitungkembalian();
            }
            public void removeUpdate(DocumentEvent e) {
                hitungkembalian();
            }
            public void insertUpdate(DocumentEvent e) {
                hitungkembalian();
            }
        
        });
    }
    
    public void hitungkembalian() {
        try {
            int totalHarga = Integer.parseInt(tf_total.getText());
            int cash = Integer.parseInt(tf_cash.getText());
            int kembalian = cash - totalHarga;

            tf_kembali.setText(String.valueOf(kembalian));
        } catch (NumberFormatException ex) {
            tf_kembali.setText("");
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngrp_menu = new javax.swing.ButtonGroup();
        btngrp_topping = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        roti1 = new javax.swing.JRadioButton();
        roti3 = new javax.swing.JRadioButton();
        roti4 = new javax.swing.JRadioButton();
        roti5 = new javax.swing.JRadioButton();
        roti8 = new javax.swing.JRadioButton();
        roti9 = new javax.swing.JRadioButton();
        roti10 = new javax.swing.JRadioButton();
        roti7 = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        topping1 = new javax.swing.JRadioButton();
        topping3 = new javax.swing.JRadioButton();
        topping2 = new javax.swing.JRadioButton();
        topping4 = new javax.swing.JRadioButton();
        topping6 = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tf_jumlah = new javax.swing.JTextField();
        btn_minus = new javax.swing.JButton();
        btn_plus = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        tf_total = new javax.swing.JTextField();
        btn_hitung = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        tf_cash = new javax.swing.JTextField();
        tf_kembali = new javax.swing.JTextField();
        btn_reset = new javax.swing.JButton();
        btn_beli = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 51, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 5));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\USEr\\Downloads\\image.png")); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 140, 116));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\USEr\\Documents\\SEMESTER 3\\PEMVIS\\PRAKTIKUM\\PRAKTIKUM PERTEMUAN\\pertemuan-2\\image.png")); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(715, 17, -1, 124));

        jLabel3.setFont(new java.awt.Font("Edwardian Script ITC", 1, 60)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Pâtisserie Étoile");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(292, 37, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 899, -1));

        jPanel2.setBackground(new java.awt.Color(255, 204, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 5));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Leelawadee UI", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Menu Roti");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 10, -1, -1));

        btngrp_menu.add(roti1);
        roti1.setFont(new java.awt.Font("Eras Medium ITC", 0, 12)); // NOI18N
        roti1.setText("Croissant au Beurre - Rp 25.000");
        jPanel2.add(roti1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        btngrp_menu.add(roti3);
        roti3.setFont(new java.awt.Font("Eras Medium ITC", 0, 12)); // NOI18N
        roti3.setText("Baguette Traditionnelle - Rp 20.000");
        jPanel2.add(roti3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, -1, -1));

        btngrp_menu.add(roti4);
        roti4.setFont(new java.awt.Font("Eras Medium ITC", 0, 12)); // NOI18N
        roti4.setText("Brioche à Tête - Rp 30.000");
        jPanel2.add(roti4, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 60, -1, -1));

        btngrp_menu.add(roti5);
        roti5.setFont(new java.awt.Font("Eras Medium ITC", 0, 12)); // NOI18N
        roti5.setText("Chausson aux - Rp 32.000");
        jPanel2.add(roti5, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 60, -1, -1));

        btngrp_menu.add(roti8);
        roti8.setFont(new java.awt.Font("Eras Medium ITC", 0, 12)); // NOI18N
        roti8.setText("Tarte aux Framboises - Rp 40.000");
        jPanel2.add(roti8, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, -1, -1));

        btngrp_menu.add(roti9);
        roti9.setFont(new java.awt.Font("Eras Medium ITC", 0, 12)); // NOI18N
        roti9.setText("Fougasse Provençal - Rp 30.000");
        jPanel2.add(roti9, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 120, -1, -1));

        btngrp_menu.add(roti10);
        roti10.setFont(new java.awt.Font("Eras Medium ITC", 0, 12)); // NOI18N
        roti10.setText("Galette des Rois - Rp 45.000");
        jPanel2.add(roti10, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 120, -1, -1));

        btngrp_menu.add(roti7);
        roti7.setFont(new java.awt.Font("Eras Medium ITC", 0, 12)); // NOI18N
        roti7.setText("Pain aux Raisins - Rp 28.000");
        jPanel2.add(roti7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("----------------------------------------------------------------------------------------------------------------");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 450, -1, -1));

        jLabel6.setFont(new java.awt.Font("Leelawadee UI", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Total");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 360, -1, -1));

        btngrp_topping.add(topping1);
        topping1.setFont(new java.awt.Font("Eras Medium ITC", 0, 12)); // NOI18N
        topping1.setText("Almond slices - Rp 5.000");
        jPanel2.add(topping1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, -1, -1));

        btngrp_topping.add(topping3);
        topping3.setFont(new java.awt.Font("Eras Medium ITC", 0, 12)); // NOI18N
        topping3.setText("Powdered sugar - Rp 3.000");
        jPanel2.add(topping3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 240, -1, -1));

        btngrp_topping.add(topping2);
        topping2.setFont(new java.awt.Font("Eras Medium ITC", 0, 12)); // NOI18N
        topping2.setText("Chocolate drizzle - Rp 7.000");
        jPanel2.add(topping2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, -1, -1));

        btngrp_topping.add(topping4);
        topping4.setFont(new java.awt.Font("Eras Medium ITC", 0, 12)); // NOI18N
        topping4.setText("Fresh berries - Rp 10.000");
        jPanel2.add(topping4, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 240, -1, -1));

        btngrp_topping.add(topping6);
        topping6.setFont(new java.awt.Font("Eras Medium ITC", 0, 12)); // NOI18N
        topping6.setText("No Topping");
        jPanel2.add(topping6, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 280, -1, -1));

        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("----------------------------------------------------------------------------------------------------------------");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, -1, -1));

        jLabel8.setFont(new java.awt.Font("Leelawadee UI", 1, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Topping");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 200, -1, -1));
        jPanel2.add(tf_jumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 400, 30, 30));

        btn_minus.setText("-");
        btn_minus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_minusActionPerformed(evt);
            }
        });
        jPanel2.add(btn_minus, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, 40, 30));

        btn_plus.setText("+");
        btn_plus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_plusActionPerformed(evt);
            }
        });
        jPanel2.add(btn_plus, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 400, -1, 30));

        jLabel9.setFont(new java.awt.Font("Leelawadee UI", 1, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Kembali");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 460, -1, -1));
        jPanel2.add(tf_total, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 400, 80, 30));

        btn_hitung.setText("Hitung");
        btn_hitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hitungActionPerformed(evt);
            }
        });
        jPanel2.add(btn_hitung, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 400, 80, 30));

        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("----------------------------------------------------------------------------------------------------------------");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 330, -1, -1));

        jLabel11.setFont(new java.awt.Font("Leelawadee UI", 1, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Jumlah");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 360, -1, -1));

        jLabel12.setFont(new java.awt.Font("Leelawadee UI", 1, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Cash");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 460, -1, -1));
        jPanel2.add(tf_cash, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 490, 80, 30));
        jPanel2.add(tf_kembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 490, 80, 30));

        btn_reset.setText("Reset");
        btn_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resetActionPerformed(evt);
            }
        });
        jPanel2.add(btn_reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 530, -1, -1));

        btn_beli.setText("Beli");
        btn_beli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_beliActionPerformed(evt);
            }
        });
        jPanel2.add(btn_beli, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 530, 60, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 138, 899, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_plusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_plusActionPerformed
        int jumlah = Integer.parseInt(tf_jumlah.getText()); 
        jumlah++;  
        tf_jumlah.setText(String.valueOf(jumlah));
    
        hitung();
    }//GEN-LAST:event_btn_plusActionPerformed

    private void btn_minusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_minusActionPerformed
        int jumlah = Integer.parseInt(tf_jumlah.getText());  
        if(jumlah > 1) {  
            jumlah--;  
            tf_jumlah.setText(String.valueOf(jumlah));  
        
            hitung();
        }
    }//GEN-LAST:event_btn_minusActionPerformed
    
    private void hitung(){
        int roti = 0;
        int topping=0;
        
        if(roti1.isSelected()){
            roti= 25000;
        }else if(roti3.isSelected()){
            roti= 20000;
        }else if(roti4.isSelected()){
            roti= 30000;
        }else if(roti5.isSelected()){
            roti= 32000;
        }else if(roti7.isSelected()){
            roti= 28000;
        }else if(roti8.isSelected()){
            roti= 40000;
        }else if(roti9.isSelected()){
            roti= 30000;
        }else if(roti10.isSelected()){
            roti= 45000;
        }else{
            JOptionPane.showMessageDialog(null, "pilih salah satu menu duluuu yaaaaaa!!", "-_-", JOptionPane.WARNING_MESSAGE);
        }
        
        if(topping1.isSelected()){
            topping= 5000;
        }else if(topping2.isSelected()){
            topping= 7000;
        }else if(topping3.isSelected()){
            topping= 3000;
        }else if(topping4.isSelected()){
            topping= 10000;
        }else if(topping6.isSelected()){
            topping= 0;
        }else{
            JOptionPane.showMessageDialog(null, "pilih salah satu toppingnya kakkk!!", "-_-", JOptionPane.WARNING_MESSAGE);
        }
        
        int jumlah = Integer.parseInt(tf_jumlah.getText());
        int totalHarga = (roti + topping) * jumlah;
        
        if (totalHarga > 100000) {
        totalHarga = totalHarga - (totalHarga * 5 / 100); 
        }
        
        tf_total.setText(String.valueOf(totalHarga));
    }
    
    private void btn_hitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hitungActionPerformed
        hitung();
        
        btn_plus.setEnabled(true);
        btn_minus.setEnabled(true);
    }//GEN-LAST:event_btn_hitungActionPerformed

    private void btn_beliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_beliActionPerformed
        int kembalian = Integer.parseInt(tf_kembali.getText());
        
        if (kembalian < 0) {
                JOptionPane.showMessageDialog(null, "uang yang kakak masukkan kurangg hiks!! tolong input ulang yaa kak><", "permisi kak....", JOptionPane.WARNING_MESSAGE);
                tf_cash.setText("");
        }else{
            String pesanann=tf_total.getText();
            String bayar=tf_cash.getText();
            String kembalii=tf_kembali.getText();
            
            int pesanan=Integer.parseInt(pesanann);
            int cash=Integer.parseInt(bayar);
            int kembali=Integer.parseInt(kembalii);
            
            String pesan= "total pesanan:"+pesanan+"\n"+
                          "bayar               :"+cash+"\n"+
                          "kembali          :"+kembali+"\n"+
                          ""+"\n"+
                          "grazie><";
            
            int confirm = JOptionPane.showOptionDialog(this,
                "kakak sudah yakin dengan pesanan kakak???",
                "halo kakkk",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE, null, null, null);
                
            if(confirm == JOptionPane.YES_OPTION){
                JOptionPane.showMessageDialog(null, pesan, "Je vous remercie",JOptionPane.INFORMATION_MESSAGE);
                
                int confirmm = JOptionPane.showOptionDialog(this,
                "mau beli lagi atau tidak kak???",
                "aku mw tanya nih",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE, null, null, null);
                
                if(confirmm == JOptionPane.NO_OPTION){
                    System.exit(0);
                }else{
                    tf_jumlah.setText("1");
                    tf_cash.setText("");
                    tf_kembali.setText("");
                    tf_total.setText("");
                    btngrp_menu.clearSelection();  
                    btngrp_topping.clearSelection();
                }
            }
            
        }
    }//GEN-LAST:event_btn_beliActionPerformed

    private void btn_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resetActionPerformed
        tf_jumlah.setText("1");
        tf_cash.setText("");
        tf_kembali.setText("");
        tf_total.setText("");
        btngrp_menu.clearSelection();  
        btngrp_topping.clearSelection();
        btn_plus.setEnabled(false);
        btn_minus.setEnabled(false);
    }//GEN-LAST:event_btn_resetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TokoRotii.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TokoRotii.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TokoRotii.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TokoRotii.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TokoRotii().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_beli;
    private javax.swing.JButton btn_hitung;
    private javax.swing.JButton btn_minus;
    private javax.swing.JButton btn_plus;
    private javax.swing.JButton btn_reset;
    private javax.swing.ButtonGroup btngrp_menu;
    private javax.swing.ButtonGroup btngrp_topping;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton roti1;
    private javax.swing.JRadioButton roti10;
    private javax.swing.JRadioButton roti3;
    private javax.swing.JRadioButton roti4;
    private javax.swing.JRadioButton roti5;
    private javax.swing.JRadioButton roti7;
    private javax.swing.JRadioButton roti8;
    private javax.swing.JRadioButton roti9;
    private javax.swing.JTextField tf_cash;
    private javax.swing.JTextField tf_jumlah;
    private javax.swing.JTextField tf_kembali;
    private javax.swing.JTextField tf_total;
    private javax.swing.JRadioButton topping1;
    private javax.swing.JRadioButton topping2;
    private javax.swing.JRadioButton topping3;
    private javax.swing.JRadioButton topping4;
    private javax.swing.JRadioButton topping6;
    // End of variables declaration//GEN-END:variables

}
