/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tp1;

/**
 *
 * @author User
 */
public class tp1formulir extends javax.swing.JFrame {



//    String nama2, tempat2,tanggal2,alamat2,telepon2,email2,prodi2,fakultas2 ;
        tp1formulir() {
//            String nama2;
//            String tempat2;
//            String tanggal2;
//            String alamat2;
//            int telepon2;
//            String email2;
//            String prodi2;
            
            
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        nama1 = new javax.swing.JLabel();
        tempat1 = new javax.swing.JLabel();
        tanggal1 = new javax.swing.JLabel();
        jenis1 = new javax.swing.JLabel();
        alamat1 = new javax.swing.JLabel();
        telepon1 = new javax.swing.JLabel();
        email1 = new javax.swing.JLabel();
        prodi1 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        nama2 = new javax.swing.JTextField();
        tempat2 = new javax.swing.JTextField();
        tanggal2 = new javax.swing.JTextField();
        fakultas2 = new javax.swing.JTextField();
        jbjenis = new javax.swing.JTextField();
        telepon2 = new javax.swing.JTextField();
        email2 = new javax.swing.JTextField();
        prodi2 = new javax.swing.JTextField();
        batal = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        alamat2 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(153, 255, 51));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        jPanel3.setForeground(new java.awt.Color(153, 153, 153));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("FORMULIR PENDAFTARAN MAHASISWA");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 6, 376, 26));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("UNIVERSITAS TRUNOJOYO MADURA");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 38, 376, 26));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Jl. Raya Telang, PO. Box. 2 Kamal, Bangkalan - Madura ");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 70, 376, 26));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Telp : (031) 3011146, Fax. (031) 3011506");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 102, 376, 26));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Pictures\\logo\\Logo_Biosfer-removebg-preview (1).png")); // NOI18N
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 142, 110));

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Pictures\\logo\\thPA-removebg-preview.png")); // NOI18N
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(554, 6, -1, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 140));

        jPanel7.setBackground(new java.awt.Color(153, 255, 51));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nama1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        nama1.setText("Nama :                      ");
        jPanel7.add(nama1, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 76, 111, -1));

        tempat1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        tempat1.setText("Tempat Lahir :");
        jPanel7.add(tempat1, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 104, 111, -1));

        tanggal1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        tanggal1.setText("Tanggal Lahir :");
        jPanel7.add(tanggal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 132, 111, -1));

        jenis1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jenis1.setText("Jenis Kelamin :");
        jPanel7.add(jenis1, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 159, -1, -1));

        alamat1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        alamat1.setText("Alamat :");
        jPanel7.add(alamat1, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 187, 111, -1));

        telepon1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        telepon1.setText("No. Telp :");
        jPanel7.add(telepon1, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 215, 111, -1));

        email1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        email1.setText("Email :");
        jPanel7.add(email1, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 243, 111, -1));

        prodi1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        prodi1.setText("Prodi :");
        jPanel7.add(prodi1, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 271, 111, -1));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel13.setText("Fakultas :");
        jPanel7.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 301, 111, -1));

        nama2.setEditable(false);
        nama2.setEnabled(false);
        nama2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nama2ActionPerformed(evt);
            }
        });
        jPanel7.add(nama2, new org.netbeans.lib.awtextra.AbsoluteConstraints(196, 71, 250, -1));

        tempat2.setEditable(false);
        tempat2.setBackground(new java.awt.Color(255, 255, 255));
        tempat2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tempat2ActionPerformed(evt);
            }
        });
        jPanel7.add(tempat2, new org.netbeans.lib.awtextra.AbsoluteConstraints(196, 99, 250, -1));

        tanggal2.setEditable(false);
        tanggal2.setBackground(new java.awt.Color(255, 255, 255));
        tanggal2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tanggal2ActionPerformed(evt);
            }
        });
        jPanel7.add(tanggal2, new org.netbeans.lib.awtextra.AbsoluteConstraints(196, 127, 250, -1));

        fakultas2.setEditable(false);
        fakultas2.setBackground(new java.awt.Color(255, 255, 255));
        fakultas2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fakultas2ActionPerformed(evt);
            }
        });
        jPanel7.add(fakultas2, new org.netbeans.lib.awtextra.AbsoluteConstraints(196, 294, 250, -1));

        jbjenis.setEditable(false);
        jbjenis.setBackground(new java.awt.Color(255, 255, 255));
        jbjenis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbjenisActionPerformed(evt);
            }
        });
        jPanel7.add(jbjenis, new org.netbeans.lib.awtextra.AbsoluteConstraints(196, 154, 250, -1));

        telepon2.setEditable(false);
        telepon2.setBackground(new java.awt.Color(255, 255, 255));
        telepon2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telepon2ActionPerformed(evt);
            }
        });
        jPanel7.add(telepon2, new org.netbeans.lib.awtextra.AbsoluteConstraints(196, 210, 250, -1));

        email2.setEditable(false);
        email2.setBackground(new java.awt.Color(255, 255, 255));
        email2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                email2ActionPerformed(evt);
            }
        });
        jPanel7.add(email2, new org.netbeans.lib.awtextra.AbsoluteConstraints(196, 238, 250, -1));

        prodi2.setEditable(false);
        prodi2.setBackground(new java.awt.Color(255, 255, 255));
        prodi2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prodi2ActionPerformed(evt);
            }
        });
        jPanel7.add(prodi2, new org.netbeans.lib.awtextra.AbsoluteConstraints(196, 266, 250, -1));

        batal.setText("Batal");
        batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batalActionPerformed(evt);
            }
        });
        jPanel7.add(batal, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 350, -1, -1));

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText(" Biodata ");
        jPanel7.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 24, 367, -1));

        alamat2.setEditable(false);
        alamat2.setBackground(new java.awt.Color(255, 255, 255));
        alamat2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alamat2ActionPerformed(evt);
            }
        });
        jPanel7.add(alamat2, new org.netbeans.lib.awtextra.AbsoluteConstraints(196, 182, 250, -1));

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 690, 390));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 31, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 106, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nama2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nama2ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_nama2ActionPerformed

    private void tempat2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tempat2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tempat2ActionPerformed

    private void fakultas2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fakultas2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fakultas2ActionPerformed

    private void jbjenisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbjenisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbjenisActionPerformed

    private void telepon2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telepon2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telepon2ActionPerformed

    private void email2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_email2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_email2ActionPerformed

    private void prodi2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prodi2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prodi2ActionPerformed

    private void batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batalActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_batalActionPerformed

    private void tanggal2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tanggal2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tanggal2ActionPerformed

    private void alamat2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alamat2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alamat2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tp1formulir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tp1formulir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tp1formulir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tp1formulir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tp1formulir().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alamat1;
    public javax.swing.JTextField alamat2;
    private javax.swing.JButton batal;
    private javax.swing.JLabel email1;
    public javax.swing.JTextField email2;
    public javax.swing.JTextField fakultas2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    public javax.swing.JTextField jbjenis;
    private javax.swing.JLabel jenis1;
    private javax.swing.JLabel nama1;
    public javax.swing.JTextField nama2;
    private javax.swing.JLabel prodi1;
    public javax.swing.JTextField prodi2;
    private javax.swing.JLabel tanggal1;
    public javax.swing.JTextField tanggal2;
    private javax.swing.JLabel telepon1;
    public javax.swing.JTextField telepon2;
    private javax.swing.JLabel tempat1;
    public javax.swing.JTextField tempat2;
    // End of variables declaration//GEN-END:variables
}
