/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package slicing;

/**
 *
 * @author USEr
 */
public class slicingg2 extends javax.swing.JFrame {

    /**
     * Creates new form slicingg2
     */
    private final slicingg previousWindow; 
    public slicingg2(String name, String tetl, String NIK, String adress, String number,
            String kill, String tatto, String gender, String healthy,String combobox, slicingg previous) {
        initComponents();
        
        namaa.setText(name);
        teteel.setText(tetl);
        nikk.setText(NIK);
        alamatt.setText(adress);
        nowaa.setText(number);
        jumkill.setText(kill);
        jumtatt.setText(tatto);
        combobox2.setSelectedItem(combobox);
        combobox2.setEnabled(false);
        namaa.setEditable(false);
        teteel.setEditable(false);
        nikk.setEditable(false);
        alamatt.setEditable(false);
        nowaa.setEditable(false);
        jumkill.setEditable(false);
        jumtatt.setEditable(false);
//        jumtatt.enable(false);
        
        if (gender.equals("Man")) {
        gender1.setSelected(true);
        } else {
        gender2.setSelected(true);
        }
        gender1.setEnabled(false);
        gender2.setEnabled(false);

        if (healthy.equals("Iya")) {
        bpjs1.setSelected(true);
        } else {
        bpjs2.setSelected(true);
        }
        bpjs1.setEnabled(false);
        bpjs2.setEnabled(false);
      
        kembali.requestFocusInWindow();
        this.previousWindow = previous; 
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        wa = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        combobox2 = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        gender1 = new javax.swing.JRadioButton();
        gender2 = new javax.swing.JRadioButton();
        namaa = new javax.swing.JTextField();
        teteel = new javax.swing.JTextField();
        nikk = new javax.swing.JTextField();
        alamatt = new javax.swing.JTextField();
        nowaa = new javax.swing.JTextField();
        jumkill = new javax.swing.JTextField();
        jumtatt = new javax.swing.JTextField();
        kembali = new javax.swing.JButton();
        bpjs1 = new javax.swing.JRadioButton();
        bpjs2 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 51), 3));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\USEr\\Documents\\SEMESTER 3\\PEMVIS\\PRAKTIKUM\\PRAKTIKUM PERTEMUAN\\pertemuan-1\\rsz_whatsapp_image_2024-09-25_at_212913_4422d6e5.jpg")); // NOI18N
        jLabel1.setText("logo");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 9, 158, 95));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\USEr\\Documents\\SEMESTER 3\\PEMVIS\\PRAKTIKUM\\PRAKTIKUM PERTEMUAN\\pertemuan-1\\rsz_whatsapp_image_2024-09-25_at_212913_78da3d57-removebg-preview.png")); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(581, 9, 118, 105));

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 16)); // NOI18N
        jLabel2.setText("FORMULIR PENDAFTARAN ANGGOTA");
        jLabel2.setMaximumSize(new java.awt.Dimension(232, 18));
        jLabel2.setMinimumSize(new java.awt.Dimension(232, 18));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(223, 27, -1, 35));

        jLabel4.setFont(new java.awt.Font("Courier New", 0, 17)); // NOI18N
        jLabel4.setText("Tokyo Manji Gang");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(298, 74, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 120));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0), 4));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Nama :");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("TTL :");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("NIK :");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Gender Lu :");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Alamat :");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, -1, -1));

        wa.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        wa.setForeground(new java.awt.Color(255, 255, 255));
        wa.setText("No. Wa :");
        jPanel2.add(wa, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Punya BPJS :");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Jumlah Kill :");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 340, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Jumlah Tatto :");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 380, -1, -1));

        combobox2.setBackground(new java.awt.Color(0, 0, 0));
        combobox2.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        combobox2.setForeground(new java.awt.Color(255, 255, 255));
        combobox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "‎", "Parang", "Clurit", "Gir", "Crowbar", "Katana", "Knuckle", "Tangan Kosong", "Lainnya", " " }));
        combobox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combobox2ActionPerformed(evt);
            }
        });
        jPanel2.add(combobox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 420, 309, -1));

        jLabel14.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Senjata Andalan :");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 420, -1, -1));

        gender1.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        gender1.setForeground(new java.awt.Color(255, 255, 255));
        gender1.setText("Man");
        jPanel2.add(gender1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 180, -1, -1));

        gender2.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        gender2.setForeground(new java.awt.Color(255, 255, 255));
        gender2.setText("Woman");
        jPanel2.add(gender2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 180, -1, -1));

        namaa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaaActionPerformed(evt);
            }
        });
        jPanel2.add(namaa, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, 309, -1));
        jPanel2.add(teteel, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, 309, -1));
        jPanel2.add(nikk, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, 309, -1));
        jPanel2.add(alamatt, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 220, 309, -1));

        nowaa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nowaaActionPerformed(evt);
            }
        });
        jPanel2.add(nowaa, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, 309, -1));

        jumkill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jumkillActionPerformed(evt);
            }
        });
        jPanel2.add(jumkill, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 340, 309, -1));

        jumtatt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jumtattActionPerformed(evt);
            }
        });
        jPanel2.add(jumtatt, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 380, 309, -1));

        kembali.setText("Kembali");
        kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembaliActionPerformed(evt);
            }
        });
        jPanel2.add(kembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 460, -1, -1));

        bpjs1.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        bpjs1.setForeground(new java.awt.Color(255, 255, 255));
        bpjs1.setText("Iya");
        jPanel2.add(bpjs1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 300, -1, -1));

        bpjs2.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        bpjs2.setForeground(new java.awt.Color(255, 255, 255));
        bpjs2.setText("Tidak");
        jPanel2.add(bpjs2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 300, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 740, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void combobox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combobox2ActionPerformed

    }//GEN-LAST:event_combobox2ActionPerformed

    private void namaaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaaActionPerformed

    private void nowaaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nowaaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nowaaActionPerformed

    private void jumkillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jumkillActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jumkillActionPerformed

    private void jumtattActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jumtattActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jumtattActionPerformed

    private void kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembaliActionPerformed
        this.setVisible(false);
        previousWindow.setVisible(true);
    }//GEN-LAST:event_kembaliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(slicingg2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(slicingg2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(slicingg2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(slicingg2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            // Here you would normally pass valid data instead of default values
            new slicingg2("Default Name", "Default TTL", "000000", "Default Address", "00000", "0", "0", "Man", "Iya","Parang", null).setVisible(true);
        }
    });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alamatt;
    private javax.swing.JRadioButton bpjs1;
    private javax.swing.JRadioButton bpjs2;
    private javax.swing.JComboBox<String> combobox2;
    private javax.swing.JRadioButton gender1;
    private javax.swing.JRadioButton gender2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jumkill;
    private javax.swing.JTextField jumtatt;
    private javax.swing.JButton kembali;
    private javax.swing.JTextField namaa;
    private javax.swing.JTextField nikk;
    private javax.swing.JTextField nowaa;
    private javax.swing.JTextField teteel;
    private javax.swing.JLabel wa;
    // End of variables declaration//GEN-END:variables
}
